# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    # var p = ...
    # new Box_int()
    movq $4, %rdi             # malloc size
    callq malloc                  # allocate memory
    pushq %rax                    # save allocated objPtr
    movq (%rsp), %rdi             # this pointer
    callq Box_int_Box_int              # call constructor
    popq %rax                     # return objPtr
    # end new Box_int()
    movq %rax, -16(%rbp)    # store to p
    # function call
    movq -16(%rbp), %rax    # load p
    pushq %rax                   # save this pointer
    movq $9, %rax           # int literal
    pushq %rax
    popq %rsi
    popq %rdi                    # this pointer
    callq Box_int_set               # method call
    # var v = ...
    # function call
    movq -16(%rbp), %rax    # load p
    pushq %rax                   # save this pointer
    popq %rdi                    # this pointer
    callq Box_int_get               # method call
    movq %rax, -24(%rbp)    # store to v
    # delete pointer
    movq -16(%rbp), %rax    # load p
    movq %rax, %rdi               # pointer to delete
    pushq %rdi                    # save pointer
    callq Box_int_dtor         # call destructor
    popq %rdi                     # restore pointer for free
    callq free                    # free memory
    # return expr
    # binary expr
    movq -24(%rbp), %rax    # load v
    pushq %rax
    movq $9, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    subq %rcx, %rax              # -
    leave
    ret
    leave
    ret
    
        .globl Box_int_Box_int
    Box_int_Box_int:
    # Function: Box_int (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax           # int literal
    pushq %rax                   # stash value
    movq -8(%rbp), %rax    # load this
    movq %rax, %rcx                # this address
    popq %rax                    # restore value
    movl %eax, 0(%rcx)    # .value = ... (offset 0)
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Box_int_set
    Box_int_set:
    # Function: set (params: 1)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq %rsi, -16(%rbp)    # param: v
    movq -16(%rbp), %rax    # load v
    pushq %rax                   # stash value
    movq -8(%rbp), %rax    # load this
    movq %rax, %rcx                # this address
    popq %rax                    # restore value
    movl %eax, 0(%rcx)    # .value = ... (offset 0)
    movq $0, %rax
    leave
    ret
    
        .globl Box_int_get
    Box_int_get:
    # Function: get (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq -8(%rbp), %rax    # load this
    movl 0(%rax), %eax    # load .value (offset 0)
    leave
    ret
    leave
    ret
    
        .globl Box_int_dtor
    Box_int_dtor:
    # Function: ~Box_int (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
