# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl Resource_Resource
    Resource_Resource:
    # Function: Resource (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $42, %rax           # int literal
    pushq %rax                   # stash value
    movq -8(%rbp), %rax    # load this
    movq %rax, %rcx                # this address
    popq %rax                    # restore value
    movl %eax, 0(%rcx)    # .value = ... (offset 0)
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Resource_get
    Resource_get:
    # Function: get (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq -8(%rbp), %rax    # load this
    movl 0(%rax), %eax    # load .value (offset 0)
    leave
    ret
    leave
    ret
    
        .globl Resource_dtor
    Resource_dtor:
    # Function: ~Resource (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax           # int literal
    pushq %rax                   # stash value
    movq -8(%rbp), %rax    # load this
    movq %rax, %rcx                # this address
    popq %rax                    # restore value
    movl %eax, 0(%rcx)    # .value = ... (offset 0)
    leave
    ret
    
        .globl VBase_VBase
    VBase_VBase:
    # Function: VBase (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV5VBase(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq $7, %rax           # int literal
    pushq %rax                   # stash value
    movq -8(%rbp), %rax    # load this
    movq %rax, %rcx                # this address
    popq %rax                    # restore value
    movl %eax, 8(%rcx)    # .tag = ... (offset 8)
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl VBase_kind
    VBase_kind:
    # Function: kind (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $1, %rax           # int literal
    leave
    ret
    leave
    ret
    
        .globl VBase_dtor
    VBase_dtor:
    # Function: ~VBase (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax           # int literal
    pushq %rax                   # stash value
    movq -8(%rbp), %rax    # load this
    movq %rax, %rcx                # this address
    popq %rax                    # restore value
    movl %eax, 8(%rcx)    # .tag = ... (offset 8)
    leave
    ret
    
        .globl UniqueResource_UniqueResource
    UniqueResource_UniqueResource:
    # Function: UniqueResource (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # new Resource()
    movq $4, %rdi             # malloc size
    callq malloc                  # allocate memory
    pushq %rax                    # save allocated objPtr
    movq (%rsp), %rdi             # this pointer
    callq Resource_Resource              # call constructor
    popq %rax                     # return objPtr
    # end new Resource()
    pushq %rax                   # stash value
    movq -8(%rbp), %rax    # load this
    movq %rax, %rcx                # this address
    popq %rax                    # restore value
    movl %eax, 0(%rcx)    # .ptr = ... (offset 0)
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl UniqueResource_get
    UniqueResource_get:
    # Function: get (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    # function call
    movq -8(%rbp), %rax    # load this
    movl 0(%rax), %eax    # load .ptr (offset 0)
    pushq %rax                   # save this pointer
    popq %rdi                    # this pointer
    callq Resource_get               # method call
    leave
    ret
    leave
    ret
    
        .globl UniqueResource_dtor
    UniqueResource_dtor:
    # Function: ~UniqueResource (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # delete pointer
    movq -8(%rbp), %rax    # load this
    movl 0(%rax), %eax    # load .ptr (offset 0)
    movq %rax, %rdi               # pointer to delete
    pushq %rdi                    # save pointer
    callq Resource_dtor         # call destructor
    popq %rdi                     # restore pointer for free
    callq free                    # free memory
    leave
    ret
    
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    # var v = ...
    movq $0, %rax           # int literal
    movq %rax, -16(%rbp)    # store to v
    # stack object r1 : Resource (8 bytes, RAII)
    movq $0, -24(%rbp)    # zero-init r1 +0
    leaq -24(%rbp), %rdi    # this = &r1
    callq Resource_Resource          # call constructor
    # stack object r2 : Resource (8 bytes, RAII)
    movq $0, -32(%rbp)    # zero-init r2 +0
    leaq -32(%rbp), %rdi    # this = &r2
    callq Resource_Resource          # call constructor
    # function call
    leaq -24(%rbp), %rax    # &r1 (stack object address)
    pushq %rax                   # save this pointer
    popq %rdi                    # this pointer
    callq Resource_get               # method call
    movq %rax, -16(%rbp)    # v = ...
    # ~Resource() auto at block end (RAII, reverse order)
    leaq -32(%rbp), %rdi    # this = &stack object
    callq Resource_dtor          # call destructor
    # ~Resource() auto at block end (RAII, reverse order)
    leaq -24(%rbp), %rdi    # this = &stack object
    callq Resource_dtor          # call destructor
    # stack object b : VBase (16 bytes, RAII)
    movq $0, -48(%rbp)    # zero-init b +0
    movq $0, -40(%rbp)    # zero-init b +8
    leaq _ZTV5VBase(%rip), %rcx    # vtable address
    addq $16, %rcx              # skip to vtable[0]
    movq %rcx, -48(%rbp)    # install _vptr (stack obj)
    leaq -48(%rbp), %rdi    # this = &b
    callq VBase_VBase          # call constructor
    # binary expr
    movq -16(%rbp), %rax    # load v
    pushq %rax
    # function call
    leaq -48(%rbp), %rax    # &b (stack object address)
    movq %rax, %rdi            # this = object address
    # VIRTUAL CALL: VBase::kind (vtable[0])
    pushq %rdi                   # save this (object address)
    popq %rdi                    # this pointer (restored)
    # ═══ Virtual Call Step (a): Read _vptr from object ═══
    movq (%rdi), %rax            # rax = obj._vptr (at offset 0)
    # ═══ Virtual Call Step (b): Load function address from vtable ═══
    movq 0(%rax), %rax       # rax = vtable[0] (offset 0)
    # ═══ Virtual Call Step (c): Jump to the real function ═══
    callq *%rax                  # indirect call via vtable
    # END VIRTUAL CALL VBase::kind
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    movq %rax, -16(%rbp)    # v = ...
    # ~VBase() auto at block end (RAII, reverse order)
    leaq -48(%rbp), %rdi    # this = &stack object
    # VIRTUAL CALL: VBase::dtor (vtable[1])
    pushq %rdi                   # save this (object address)
    popq %rdi                    # this pointer (restored)
    # ═══ Virtual Call Step (a): Read _vptr from object ═══
    movq (%rdi), %rax            # rax = obj._vptr (at offset 0)
    # ═══ Virtual Call Step (b): Load function address from vtable ═══
    movq 8(%rax), %rax       # rax = vtable[1] (offset 8)
    # ═══ Virtual Call Step (c): Jump to the real function ═══
    callq *%rax                  # indirect call via vtable
    # END VIRTUAL CALL VBase::dtor
    # stack object u : UniqueResource (8 bytes, RAII)
    movq $0, -56(%rbp)    # zero-init u +0
    leaq -56(%rbp), %rdi    # this = &u
    callq UniqueResource_UniqueResource          # call constructor
    # binary expr
    movq -16(%rbp), %rax    # load v
    pushq %rax
    # function call
    leaq -56(%rbp), %rax    # &u (stack object address)
    pushq %rax                   # save this pointer
    popq %rdi                    # this pointer
    callq UniqueResource_get               # method call
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    movq %rax, -16(%rbp)    # v = ...
    # ~UniqueResource() auto at block end (RAII, reverse order)
    leaq -56(%rbp), %rdi    # this = &stack object
    callq UniqueResource_dtor          # call destructor
    # return expr
    # binary expr
    movq -16(%rbp), %rax    # load v
    pushq %rax
    movq $85, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    subq %rcx, %rax              # -
    leave
    ret
    leave
    ret
    

    .data
    .globl _ZTV5VBase
    .align 8
_ZTV5VBase:
    .quad 0                    # offset to top
    .quad _ZTI5VBase       # RTTI type_info pointer (vtable[-1])
    .quad VBase_kind   # vtable[0]: VBase_kind
    .quad VBase_dtor   # vtable[1]: VBase_dtor

    .globl _ZTI5VBase
    .align 8
_ZTI5VBase:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_VBase                 # type name string
    .quad 0                    # no base class


    .section .rodata
.Ltype_name_VBase:
    .string "VBase"           # type name
