# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl main             # 导出函数符号，使链接器可见
    main:                       # 函数入口标签
    # Function: main (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    # var ok = ...
    movq $0, %rax           # 整数字面量载入 rax
    movq %rax, -16(%rbp)       # 存储到局部变量 ok
    # var p = ...
    # function call
    movq $8, %rax           # 整数字面量载入 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rdi                   # 逆序弹出实参到寄存器
    callq malloc                  # 调用函数 malloc
    movq %rax, -24(%rbp)       # 存储到局部变量 p
    # if condition
    # binary expr
    movq -24(%rbp), %rax    # 加载局部变量 p 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    xorq %rax, %rax             # nullptr = 0（x86 惯用自异或清零）
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_1                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # binary expr
    movq -16(%rbp), %rax    # 加载局部变量 ok 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $1, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    movq %rax, -16(%rbp)       # 赋值局部变量 ok
    endif_1:                        # endif 标签
    # var q = ...
    # function call
    movq $8, %rax           # 整数字面量载入 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rdi                   # 逆序弹出实参到寄存器
    callq malloc                  # 调用函数 malloc
    movq %rax, -32(%rbp)       # 存储到局部变量 q
    # var r = ...
    # function call
    movq -24(%rbp), %rax    # 加载局部变量 p 到 rax
    pushq %rax                  # 实参值压栈暂存
    movq -32(%rbp), %rax    # 加载局部变量 q 到 rax
    pushq %rax                  # 实参值压栈暂存
    movq $8, %rax           # 整数字面量载入 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rdx                   # 逆序弹出实参到寄存器
    popq %rsi                   # 逆序弹出实参到寄存器
    popq %rdi                   # 逆序弹出实参到寄存器
    callq memcpy                  # 调用函数 memcpy
    movq %rax, -40(%rbp)       # 存储到局部变量 r
    # if condition
    # binary expr
    movq -40(%rbp), %rax    # 加载局部变量 r 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq -24(%rbp), %rax    # 加载局部变量 p 到 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    sete %al                    # 相等时 al = 1（ZF=1）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_3                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # binary expr
    movq -16(%rbp), %rax    # 加载局部变量 ok 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $1, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    movq %rax, -16(%rbp)       # 赋值局部变量 ok
    endif_3:                        # endif 标签
    # var p2 = ...
    # function call
    movq -24(%rbp), %rax    # 加载局部变量 p 到 rax
    pushq %rax                  # 实参值压栈暂存
    movq $16, %rax           # 整数字面量载入 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rsi                   # 逆序弹出实参到寄存器
    popq %rdi                   # 逆序弹出实参到寄存器
    callq realloc                  # 调用函数 realloc
    movq %rax, -48(%rbp)       # 存储到局部变量 p2
    # function call
    movq -48(%rbp), %rax    # 加载局部变量 p2 到 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rdi                   # 逆序弹出实参到寄存器
    callq free                  # 调用函数 free
    # function call
    movq -32(%rbp), %rax    # 加载局部变量 q 到 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rdi                   # 逆序弹出实参到寄存器
    callq free                  # 调用函数 free
    # return expr
    # binary expr
    movq -16(%rbp), %rax    # 加载局部变量 ok 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $2, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    subq %rcx, %rax             # 减法：rax = rax - rcx
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
