if(EXISTS "/home/magene/runtime/cppproject/mycompiler/build-linux/unit_tests[1]_tests.cmake")
  include("/home/magene/runtime/cppproject/mycompiler/build-linux/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
