# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl Base_dtor
    Base_dtor:
    # Function: ~Base (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    movq %rdi, -8(%rbp)
    leave
    ret
    
        .globl Base_Base
    Base_Base:
    # Function: Base (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV4Base(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Derived_Derived
    Derived_Derived:
    # Function: Derived (params: 2)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    movq %rdi, -8(%rbp)
    movq %rsi, -16(%rbp)    # param: i
    movq %rdx, -24(%rbp)    # param: s
    movq -8(%rbp), %rax    # this
    leaq _ZTV7Derived(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq -16(%rbp), %rax    # load i
    movq %rax, id(%rip)    # global id = ...
    movq -24(%rbp), %rax    # load s
    movq %rax, score(%rip)    # global score = ...
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Derived_dtor
    Derived_dtor:
    # Function: ~Derived (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    movq %rdi, -8(%rbp)
    leave
    ret
    
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    # var b = ...
    # new Derived()
    movq $8, %rdi             # malloc size
    callq malloc                  # allocate memory
    pushq %rax                    # save allocated objPtr
    leaq _ZTV7Derived(%rip), %rcx    # vtable address
    addq $16, %rcx              # skip to vtable[0]
    movq (%rsp), %rax           # load objPtr
    movq %rcx, (%rax)           # obj._vptr = vtable
    movq $1, %rax           # int literal
    pushq %rax
    movq $100, %rax           # int literal
    pushq %rax
    popq %rdx
    popq %rsi
    movq (%rsp), %rdi             # this pointer
    callq Derived_Derived              # call constructor
    popq %rax                     # return objPtr
    # end new Derived()
    movq %rax, -16(%rbp)    # store to b
    # delete pointer
    movq -16(%rbp), %rax    # load b
    movq %rax, %rdi               # pointer to delete
    pushq %rdi                    # save pointer
    # VIRTUAL CALL: Base::dtor (vtable[0])
    movq %rdi, %rbx              # save object pointer
    movq %rbx, %rdi              # this pointer
    # ═══ Virtual Call Step (a): Read _vptr from object ═══
    movq (%rdi), %rax            # rax = obj._vptr (at offset 0)
    # ═══ Virtual Call Step (b): Load function address from vtable ═══
    movq 16(%rax), %rax       # rax = vtable[0] (offset 16)
    # ═══ Virtual Call Step (c): Jump to the real function ═══
    callq *%rax                  # indirect call via vtable
    # END VIRTUAL CALL Base::dtor
    popq %rdi                     # restore pointer for free
    callq free                    # free memory
    # return expr
    movq $0, %rax           # int literal
    leave
    ret
    leave
    ret
    

    .data
    .globl _ZTV7Derived
    .align 8
_ZTV7Derived:
    .quad 0                    # offset to top
    .quad _ZTI7Derived       # RTTI type_info pointer (vtable[-1])
    .quad Derived_dtor   # vtable[0]: Derived_dtor

    .globl _ZTI7Derived
    .align 8
_ZTI7Derived:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Derived                 # type name string

    .globl _ZTV4Base
    .align 8
_ZTV4Base:
    .quad 0                    # offset to top
    .quad _ZTI4Base       # RTTI type_info pointer (vtable[-1])
    .quad Base_dtor   # vtable[0]: Base_dtor

    .globl _ZTI4Base
    .align 8
_ZTI4Base:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Base                 # type name string


    .section .rodata
.Ltype_name_Derived:
    .string "Derived"           # type name
.Ltype_name_Base:
    .string "Base"           # type name
