# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    # return expr
    # binary expr
    # function call
    movq $21, %rax           # int literal
    pushq %rax
    popq %rdi
    callq _Z5twiceIiE               # function call
    pushq %rax
    movq $42, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    subq %rcx, %rax              # -
    leave
    ret
    leave
    ret
    
        .globl _Z5twiceIiE
    _Z5twiceIiE:
    # Function: twice (params: 1)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    movq %rdi, -8(%rbp)    # param: x
    # return expr
    # binary expr
    movq -8(%rbp), %rax    # load x
    pushq %rax
    movq -8(%rbp), %rax    # load x
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    leave
    ret
    leave
    ret
    
