# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl square
    square:
    # Function: square (params: 1)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    movq %rdi, -8(%rbp)    # param: x
    # return expr
    # binary expr
    movq -8(%rbp), %rax    # load x
    pushq %rax
    movq -8(%rbp), %rax    # load x
    movq %rax, %rcx
    popq %rax
    imulq %rcx, %rax             # *
    leave
    ret
    leave
    ret
    
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    # return expr
    # binary expr
    # binary expr
    # function call
    movq $6, %rax           # int literal
    pushq %rax
    popq %rdi
    callq square               # function call
    pushq %rax
    movq $7, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    pushq %rax
    movq $43, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    subq %rcx, %rax              # -
    leave
    ret
    leave
    ret
    
