# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl Animal_speak
    Animal_speak:
    # Function: speak (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $0, %rax           # int literal
    leave
    ret
    
        .globl Animal_Animal
    Animal_Animal:
    # Function: Animal (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV6Animal(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install primary _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Animal_dtor
    Animal_dtor:
    # Function: ~Animal (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl Dog_speak
    Dog_speak:
    # Function: speak (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $1, %rax           # int literal
    leave
    ret
    
        .globl Dog_Dog
    Dog_Dog:
    # Function: Dog (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV3Dog(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install primary _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Dog_dtor
    Dog_dtor:
    # Function: ~Dog (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    # var d = ...
    # new Dog()
    movq $24, %rdi             # malloc size
    callq malloc                  # allocate memory
    pushq %rax                    # save allocated objPtr
    leaq _ZTV3Dog(%rip), %rcx    # vtable address
    addq $16, %rcx              # skip to vtable[0]
    movq (%rsp), %rax           # load objPtr
    movq %rcx, (%rax)           # obj._vptr = vtable (primary)
    movq (%rsp), %rdi             # this pointer
    callq Dog_Dog              # call constructor
    popq %rax                     # return objPtr
    # end new Dog()
    movq %rax, -16(%rbp)    # store to d
    movq $30, %rax           # int literal
    # member assign: .speed = ...
    movq -16(%rbp), %rax    # load d
    movq %rax, %rcx                # object address
    movq $30, %rax           # int literal
    movl %eax, 16(%rcx)    # .speed (offset 16)
    # var a = ...
    # dynamic_cast<Animal*>(operand) —— 运行时 RTTI 检查
    movq -16(%rbp), %rax    # load d
    movq %rax, %rdi              # arg1: object pointer
    leaq _ZTI6Animal(%rip), %rsi    # arg2: target typeinfo
    callq __minicc_dynamic_cast  # runtime RTTI walk
    # %rax = 成功:原指针 / 失败:0 (Animal) 
    movq %rax, -24(%rbp)    # store to a
    # if condition
    # binary expr
    movq -24(%rbp), %rax    # load a
    pushq %rax
    xorq %rax, %rax                # nullptr = 0
    movq %rax, %rcx
    popq %rax
    cmpq %rcx, %rax
    sete %al                     # ==
    movzbq %al, %rax
    testq %rax, %rax
    je endif_1
    # then branch
    # return expr
    movq $1, %rax           # int literal
    leave
    ret
    endif_1:
    # var d2 = ...
    # dynamic_cast<Dog*>(operand) —— 运行时 RTTI 检查
    movq -24(%rbp), %rax    # load a
    movq %rax, %rdi              # arg1: object pointer
    leaq _ZTI3Dog(%rip), %rsi    # arg2: target typeinfo
    callq __minicc_dynamic_cast  # runtime RTTI walk
    # %rax = 成功:原指针 / 失败:0 (Dog) 
    movq %rax, -32(%rbp)    # store to d2
    # if condition
    # binary expr
    movq -32(%rbp), %rax    # load d2
    pushq %rax
    xorq %rax, %rax                # nullptr = 0
    movq %rax, %rcx
    popq %rax
    cmpq %rcx, %rax
    sete %al                     # ==
    movzbq %al, %rax
    testq %rax, %rax
    je endif_3
    # then branch
    # return expr
    movq $2, %rax           # int literal
    leave
    ret
    endif_3:
    # if condition
    # binary expr
    # member access: .speed
    movq -32(%rbp), %rax    # load d2
    movl 16(%rax), %eax    # .speed (offset 16, 4B)
    pushq %rax
    movq $30, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    cmpq %rcx, %rax
    setne %al                    # !=
    movzbq %al, %rax
    testq %rax, %rax
    je endif_5
    # then branch
    # return expr
    movq $3, %rax           # int literal
    leave
    ret
    endif_5:
    # if condition
    # binary expr
    # function call
    movq -32(%rbp), %rax    # load d2
    movq %rax, %rdi            # this = object address
    # VIRTUAL CALL: Dog::speak (vtable[0])
    pushq %rdi                   # save this (object address)
    popq %rdi                    # this pointer (restored)
    # ═══ Virtual Call Step (a): Read _vptr from object ═══
    movq (%rdi), %rax            # rax = obj._vptr (at offset 0)
    # ═══ Virtual Call Step (b): Load function address from vtable ═══
    movq 0(%rax), %rax       # rax = vtable[0] (offset 0)
    # ═══ Virtual Call Step (c): Jump to the real function ═══
    callq *%rax                  # indirect call via vtable
    # END VIRTUAL CALL Dog::speak
    pushq %rax
    movq $1, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    cmpq %rcx, %rax
    setne %al                    # !=
    movzbq %al, %rax
    testq %rax, %rax
    je endif_7
    # then branch
    # return expr
    movq $4, %rax           # int literal
    leave
    ret
    endif_7:
    # return expr
    movq $0, %rax           # int literal
    leave
    ret
    
    # __minicc_dynamic_cast(obj, target_typeinfo) —— DFS RTTI 树匹配（多继承版）
    __minicc_dynamic_cast:
    testq %rdi, %rdi             # 空对象直接失败
    je .Ldc_fail
    movq (%rdi), %rcx            # vptr
    movq -16(%rcx), %rdx         # offset-to-top (vptr[-2])
    leaq (%rdi,%rdx), %rdi       # top = obj + ott (归顶到最派生对象)
    movq -8(%rcx), %rdx          # most-derived typeinfo (vptr[-1])
    xorq %rcx, %rcx              # acc_offset = 0
    callq .Ldc_dfs               # DFS(ti, target, top, acc)
    ret
    .Ldc_dfs:
    cmpq %rsi, %rdx              # ti == target?
    je .Ldc_dfs_hit              # 命中 → return top + acc
    movq 16(%rdx), %rax          # N = base count
    testq %rax, %rax
    je .Ldc_dfs_ret0             # 叶子节点（无基类）→ 失败
    pushq %rbp
    movq %rsp, %rbp
    pushq %rdi                   # save top
    pushq %rsi                   # save target
    pushq %rdx                   # save current ti
    pushq %rcx                   # save acc_offset
    xorq %r12, %r12              # i = 0
    movq 16(%rdx), %r13          # N = base count (r13 callee-saved)
    .Ldc_dfs_loop:
    cmpq %r13, %r12              # i >= N?
    jge .Ldc_dfs_end
    movq -24(%rbp), %rdx         # reload current ti
    leaq 24(%rdx), %rax          # &bases[0]
    imulq $16, %r12, %r14        # i * 16
    addq %r14, %rax              # &bases[i]
    movq (%rax), %rdx            # bases[i].typeinfo
    movq 8(%rax), %rcx           # bases[i].offset
    addq -32(%rbp), %rcx         # acc = parent_acc + bases[i].offset
    callq .Ldc_dfs               # 递归搜索
    testq %rax, %rax
    jne .Ldc_dfs_found           # 子树命中！
    incq %r12                    # i++
    jmp .Ldc_dfs_loop
    .Ldc_dfs_end:
    xorq %rax, %rax
    addq $32, %rsp               # pop acc, ti, target, top
    popq %rbp
    ret
    .Ldc_dfs_hit:
    movq %rdi, %rax
    addq %rcx, %rax              # return top + acc_offset
    ret
    .Ldc_dfs_found:
    addq $32, %rsp
    popq %rbp
    ret
    .Ldc_dfs_ret0:
    xorq %rax, %rax
    ret
    .Ldc_fail:
    xorq %rax, %rax              # 失败：返回 0
    ret
    

    .data
    .globl _ZTV3Dog
    .align 8
_ZTV3Dog:
    .quad 0                    # offset to top (primary)
    .quad _ZTI3Dog       # RTTI type_info pointer (vtable[-1])
    .quad Dog_speak   # vtable[0]: Dog_speak

    .globl _ZTI3Dog
    .align 8
_ZTI3Dog:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Dog                 # type name string
    .quad 1                 # base class count (MI counting-style)
    .quad _ZTI6Animal                 # base[Animal] typeinfo
    .quad 0                 # base[Animal] subobject offset

    .globl _ZTV6Animal
    .align 8
_ZTV6Animal:
    .quad 0                    # offset to top (primary)
    .quad _ZTI6Animal       # RTTI type_info pointer (vtable[-1])
    .quad Animal_speak   # vtable[0]: Animal_speak

    .globl _ZTI6Animal
    .align 8
_ZTI6Animal:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Animal                 # type name string
    .quad 0                 # no base classes


    .section .rodata
.Ltype_name_Dog:
    .string "Dog"           # type name
.Ltype_name_Animal:
    .string "Animal"           # type name
