# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl Shape_area
    Shape_area:
    # Function: area (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $0, %rax           # int literal
    leave
    ret
    leave
    ret
    
        .globl Shape_Shape
    Shape_Shape:
    # Function: Shape (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV5Shape(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Shape_dtor
    Shape_dtor:
    # Function: ~Shape (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl Rectangle_area
    Rectangle_area:
    # Function: area (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $1, %rax           # int literal
    leave
    ret
    leave
    ret
    
        .globl Rectangle_Rectangle
    Rectangle_Rectangle:
    # Function: Rectangle (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV9Rectangle(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Rectangle_dtor
    Rectangle_dtor:
    # Function: ~Rectangle (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl Square_area
    Square_area:
    # Function: area (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $2, %rax           # int literal
    leave
    ret
    leave
    ret
    
        .globl Square_Square
    Square_Square:
    # Function: Square (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV6Square(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Square_dtor
    Square_dtor:
    # Function: ~Square (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl Animal_speak
    Animal_speak:
    # Function: speak (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $0, %rax           # int literal
    leave
    ret
    leave
    ret
    
        .globl Animal_Animal
    Animal_Animal:
    # Function: Animal (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV6Animal(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Animal_dtor
    Animal_dtor:
    # Function: ~Animal (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl Dog_speak
    Dog_speak:
    # Function: speak (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $1, %rax           # int literal
    leave
    ret
    leave
    ret
    
        .globl Dog_Dog
    Dog_Dog:
    # Function: Dog (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV3Dog(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Dog_dtor
    Dog_dtor:
    # Function: ~Dog (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl Cat_speak
    Cat_speak:
    # Function: speak (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $2, %rax           # int literal
    leave
    ret
    leave
    ret
    
        .globl Cat_Cat
    Cat_Cat:
    # Function: Cat (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV3Cat(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Cat_dtor
    Cat_dtor:
    # Function: ~Cat (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl Point_Point
    Point_Point:
    # Function: Point (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Point_dtor
    Point_dtor:
    # Function: ~Point (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    # var p = ...
    # new Point()
    movq $8, %rdi             # malloc size
    callq malloc                  # allocate memory
    pushq %rax                    # save allocated objPtr
    movq (%rsp), %rdi             # this pointer
    callq Point_Point              # call constructor
    popq %rax                     # return objPtr
    # end new Point()
    movq %rax, -16(%rbp)    # store to p
    movq $1, %rax           # int literal
    # member assign: .x = ...
    movq -16(%rbp), %rax    # load p
    movq %rax, %rcx                # object address
    movq $1, %rax           # int literal
    movl %eax, 0(%rcx)    # .x (offset 0)
    movq $2, %rax           # int literal
    # member assign: .y = ...
    movq -16(%rbp), %rax    # load p
    movq %rax, %rcx                # object address
    movq $2, %rax           # int literal
    movl %eax, 4(%rcx)    # .y (offset 4)
    # return expr
    movq $0, %rax           # int literal
    leave
    ret
    leave
    ret
    

    .data
    .globl _ZTV3Cat
    .align 8
_ZTV3Cat:
    .quad 0                    # offset to top
    .quad _ZTI3Cat       # RTTI type_info pointer (vtable[-1])
    .quad Cat_speak   # vtable[0]: Cat_speak

    .globl _ZTI3Cat
    .align 8
_ZTI3Cat:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Cat                 # type name string
    .quad _ZTI6Animal                 # base class typeinfo

    .globl _ZTV6Animal
    .align 8
_ZTV6Animal:
    .quad 0                    # offset to top
    .quad _ZTI6Animal       # RTTI type_info pointer (vtable[-1])
    .quad Animal_speak   # vtable[0]: Animal_speak

    .globl _ZTI6Animal
    .align 8
_ZTI6Animal:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Animal                 # type name string
    .quad 0                    # no base class

    .globl _ZTV3Dog
    .align 8
_ZTV3Dog:
    .quad 0                    # offset to top
    .quad _ZTI3Dog       # RTTI type_info pointer (vtable[-1])
    .quad Dog_speak   # vtable[0]: Dog_speak

    .globl _ZTI3Dog
    .align 8
_ZTI3Dog:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Dog                 # type name string
    .quad _ZTI6Animal                 # base class typeinfo

    .globl _ZTV6Square
    .align 8
_ZTV6Square:
    .quad 0                    # offset to top
    .quad _ZTI6Square       # RTTI type_info pointer (vtable[-1])
    .quad Square_area   # vtable[0]: Square_area

    .globl _ZTI6Square
    .align 8
_ZTI6Square:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Square                 # type name string
    .quad _ZTI9Rectangle                 # base class typeinfo

    .globl _ZTV9Rectangle
    .align 8
_ZTV9Rectangle:
    .quad 0                    # offset to top
    .quad _ZTI9Rectangle       # RTTI type_info pointer (vtable[-1])
    .quad Rectangle_area   # vtable[0]: Rectangle_area

    .globl _ZTI9Rectangle
    .align 8
_ZTI9Rectangle:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Rectangle                 # type name string
    .quad _ZTI5Shape                 # base class typeinfo

    .globl _ZTV5Shape
    .align 8
_ZTV5Shape:
    .quad 0                    # offset to top
    .quad _ZTI5Shape       # RTTI type_info pointer (vtable[-1])
    .quad Shape_area   # vtable[0]: Shape_area

    .globl _ZTI5Shape
    .align 8
_ZTI5Shape:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Shape                 # type name string
    .quad 0                    # no base class


    .section .rodata
.Ltype_name_Cat:
    .string "Cat"           # type name
.Ltype_name_Animal:
    .string "Animal"           # type name
.Ltype_name_Dog:
    .string "Dog"           # type name
.Ltype_name_Square:
    .string "Square"           # type name
.Ltype_name_Rectangle:
    .string "Rectangle"           # type name
.Ltype_name_Shape:
    .string "Shape"           # type name
