# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl Animal_speak
    Animal_speak:
    # Function: speak (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $0, %rax           # int literal
    leave
    ret
    leave
    ret
    
        .globl Animal_Animal
    Animal_Animal:
    # Function: Animal (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV6Animal(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Animal_dtor
    Animal_dtor:
    # Function: ~Animal (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl Dog_speak
    Dog_speak:
    # Function: speak (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $1, %rax           # int literal
    leave
    ret
    leave
    ret
    
        .globl Dog_Dog
    Dog_Dog:
    # Function: Dog (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV3Dog(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Dog_dtor
    Dog_dtor:
    # Function: ~Dog (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl Cat_speak
    Cat_speak:
    # Function: speak (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $2, %rax           # int literal
    leave
    ret
    leave
    ret
    
        .globl Cat_Cat
    Cat_Cat:
    # Function: Cat (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV3Cat(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Cat_dtor
    Cat_dtor:
    # Function: ~Cat (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl Puppy_speak
    Puppy_speak:
    # Function: speak (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $3, %rax           # int literal
    leave
    ret
    leave
    ret
    
        .globl Puppy_Puppy
    Puppy_Puppy:
    # Function: Puppy (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV5Puppy(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Puppy_dtor
    Puppy_dtor:
    # Function: ~Puppy (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl Puppy2_speak
    Puppy2_speak:
    # Function: speak (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $4, %rax           # int literal
    leave
    ret
    leave
    ret
    
        .globl Puppy2_Puppy2
    Puppy2_Puppy2:
    # Function: Puppy2 (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV6Puppy2(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Puppy2_dtor
    Puppy2_dtor:
    # Function: ~Puppy2 (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $80, %rsp    # frame for locals
    # var c = ...
    # new Cat()
    movq $8, %rdi             # malloc size
    callq malloc                  # allocate memory
    pushq %rax                    # save allocated objPtr
    leaq _ZTV3Cat(%rip), %rcx    # vtable address
    addq $16, %rcx              # skip to vtable[0]
    movq (%rsp), %rax           # load objPtr
    movq %rcx, (%rax)           # obj._vptr = vtable
    movq (%rsp), %rdi             # this pointer
    callq Cat_Cat              # call constructor
    popq %rax                     # return objPtr
    # end new Cat()
    movq %rax, -16(%rbp)    # store to c
    # var dog = ...
    # new Dog()
    movq $8, %rdi             # malloc size
    callq malloc                  # allocate memory
    pushq %rax                    # save allocated objPtr
    leaq _ZTV3Dog(%rip), %rcx    # vtable address
    addq $16, %rcx              # skip to vtable[0]
    movq (%rsp), %rax           # load objPtr
    movq %rcx, (%rax)           # obj._vptr = vtable
    movq (%rsp), %rdi             # this pointer
    callq Dog_Dog              # call constructor
    popq %rax                     # return objPtr
    # end new Dog()
    movq %rax, -24(%rbp)    # store to dog
    # var p2 = ...
    # new Puppy2()
    movq $16, %rdi             # malloc size
    callq malloc                  # allocate memory
    pushq %rax                    # save allocated objPtr
    leaq _ZTV6Puppy2(%rip), %rcx    # vtable address
    addq $16, %rcx              # skip to vtable[0]
    movq (%rsp), %rax           # load objPtr
    movq %rcx, (%rax)           # obj._vptr = vtable
    movq (%rsp), %rdi             # this pointer
    callq Puppy2_Puppy2              # call constructor
    popq %rax                     # return objPtr
    # end new Puppy2()
    movq %rax, -32(%rbp)    # store to p2
    # var ac = ...
    # dynamic_cast<Animal*>(operand) —— 运行时 RTTI 检查
    movq -16(%rbp), %rax    # load c
    movq %rax, %rdi              # arg1: object pointer
    leaq _ZTI6Animal(%rip), %rsi    # arg2: target typeinfo
    callq __minicc_dynamic_cast  # runtime RTTI walk
    # %rax = 成功:原指针 / 失败:0 (Animal) 
    movq %rax, -40(%rbp)    # store to ac
    # var fail1 = ...
    # dynamic_cast<Dog*>(operand) —— 运行时 RTTI 检查
    movq -40(%rbp), %rax    # load ac
    movq %rax, %rdi              # arg1: object pointer
    leaq _ZTI3Dog(%rip), %rsi    # arg2: target typeinfo
    callq __minicc_dynamic_cast  # runtime RTTI walk
    # %rax = 成功:原指针 / 失败:0 (Dog) 
    movq %rax, -48(%rbp)    # store to fail1
    # if condition
    # binary expr
    movq -48(%rbp), %rax    # load fail1
    pushq %rax
    xorq %rax, %rax                # nullptr = 0
    movq %rax, %rcx
    popq %rax
    cmpq %rcx, %rax
    setne %al                    # !=
    movzbq %al, %rax
    testq %rax, %rax
    je endif_1
    # then branch
    # return expr
    movq $1, %rax           # int literal
    leave
    ret
    endif_1:
    # var ad = ...
    # dynamic_cast<Animal*>(operand) —— 运行时 RTTI 检查
    movq -24(%rbp), %rax    # load dog
    movq %rax, %rdi              # arg1: object pointer
    leaq _ZTI6Animal(%rip), %rsi    # arg2: target typeinfo
    callq __minicc_dynamic_cast  # runtime RTTI walk
    # %rax = 成功:原指针 / 失败:0 (Animal) 
    movq %rax, -56(%rbp)    # store to ad
    # var fail2 = ...
    # dynamic_cast<Puppy*>(operand) —— 运行时 RTTI 检查
    movq -56(%rbp), %rax    # load ad
    movq %rax, %rdi              # arg1: object pointer
    leaq _ZTI5Puppy(%rip), %rsi    # arg2: target typeinfo
    callq __minicc_dynamic_cast  # runtime RTTI walk
    # %rax = 成功:原指针 / 失败:0 (Puppy) 
    movq %rax, -64(%rbp)    # store to fail2
    # if condition
    # binary expr
    movq -64(%rbp), %rax    # load fail2
    pushq %rax
    xorq %rax, %rax                # nullptr = 0
    movq %rax, %rcx
    popq %rax
    cmpq %rcx, %rax
    setne %al                    # !=
    movzbq %al, %rax
    testq %rax, %rax
    je endif_3
    # then branch
    # return expr
    movq $2, %rax           # int literal
    leave
    ret
    endif_3:
    # var ok = ...
    # dynamic_cast<Animal*>(operand) —— 运行时 RTTI 检查
    movq -32(%rbp), %rax    # load p2
    movq %rax, %rdi              # arg1: object pointer
    leaq _ZTI6Animal(%rip), %rsi    # arg2: target typeinfo
    callq __minicc_dynamic_cast  # runtime RTTI walk
    # %rax = 成功:原指针 / 失败:0 (Animal) 
    movq %rax, -72(%rbp)    # store to ok
    # if condition
    # binary expr
    movq -72(%rbp), %rax    # load ok
    pushq %rax
    xorq %rax, %rax                # nullptr = 0
    movq %rax, %rcx
    popq %rax
    cmpq %rcx, %rax
    sete %al                     # ==
    movzbq %al, %rax
    testq %rax, %rax
    je endif_5
    # then branch
    # return expr
    movq $3, %rax           # int literal
    leave
    ret
    endif_5:
    # var okMid = ...
    # dynamic_cast<Puppy*>(operand) —— 运行时 RTTI 检查
    movq -32(%rbp), %rax    # load p2
    movq %rax, %rdi              # arg1: object pointer
    leaq _ZTI5Puppy(%rip), %rsi    # arg2: target typeinfo
    callq __minicc_dynamic_cast  # runtime RTTI walk
    # %rax = 成功:原指针 / 失败:0 (Puppy) 
    movq %rax, -80(%rbp)    # store to okMid
    # if condition
    # binary expr
    movq -80(%rbp), %rax    # load okMid
    pushq %rax
    xorq %rax, %rax                # nullptr = 0
    movq %rax, %rcx
    popq %rax
    cmpq %rcx, %rax
    sete %al                     # ==
    movzbq %al, %rax
    testq %rax, %rax
    je endif_7
    # then branch
    # return expr
    movq $4, %rax           # int literal
    leave
    ret
    endif_7:
    # return expr
    movq $0, %rax           # int literal
    leave
    ret
    leave
    ret
    
    # __minicc_dynamic_cast(obj, target_typeinfo) —— RTTI 继承链匹配
    __minicc_dynamic_cast:
    testq %rdi, %rdi             # 空对象直接失败（dynamic_cast(nullptr)==nullptr）
    je .Ldc_fail
    movq (%rdi), %rcx            # %rcx = obj->_vptr
    movq -8(%rcx), %rax          # %rax = typeinfo (vtable[-1])
    .Ldc_loop:
    cmpq %rsi, %rax              # 命中目标类型？
    je .Ldc_ok
    movq 16(%rax), %rax          # 未命中：上溯到基类 typeinfo
    testq %rax, %rax             # 链尾（无基类）？
    je .Ldc_fail
    jmp .Ldc_loop
    .Ldc_ok:
    movq %rdi, %rax              # 成功：返回原指针（单继承无偏移调整）
    ret
    .Ldc_fail:
    xorq %rax, %rax              # 失败：返回 0
    ret
    

    .data
    .globl _ZTV6Puppy2
    .align 8
_ZTV6Puppy2:
    .quad 0                    # offset to top
    .quad _ZTI6Puppy2       # RTTI type_info pointer (vtable[-1])
    .quad Puppy2_speak   # vtable[0]: Puppy2_speak

    .globl _ZTI6Puppy2
    .align 8
_ZTI6Puppy2:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Puppy2                 # type name string
    .quad _ZTI5Puppy                 # base class typeinfo

    .globl _ZTV5Puppy
    .align 8
_ZTV5Puppy:
    .quad 0                    # offset to top
    .quad _ZTI5Puppy       # RTTI type_info pointer (vtable[-1])
    .quad Puppy_speak   # vtable[0]: Puppy_speak

    .globl _ZTI5Puppy
    .align 8
_ZTI5Puppy:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Puppy                 # type name string
    .quad _ZTI3Dog                 # base class typeinfo

    .globl _ZTV3Cat
    .align 8
_ZTV3Cat:
    .quad 0                    # offset to top
    .quad _ZTI3Cat       # RTTI type_info pointer (vtable[-1])
    .quad Cat_speak   # vtable[0]: Cat_speak

    .globl _ZTI3Cat
    .align 8
_ZTI3Cat:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Cat                 # type name string
    .quad _ZTI6Animal                 # base class typeinfo

    .globl _ZTV3Dog
    .align 8
_ZTV3Dog:
    .quad 0                    # offset to top
    .quad _ZTI3Dog       # RTTI type_info pointer (vtable[-1])
    .quad Dog_speak   # vtable[0]: Dog_speak

    .globl _ZTI3Dog
    .align 8
_ZTI3Dog:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Dog                 # type name string
    .quad _ZTI6Animal                 # base class typeinfo

    .globl _ZTV6Animal
    .align 8
_ZTV6Animal:
    .quad 0                    # offset to top
    .quad _ZTI6Animal       # RTTI type_info pointer (vtable[-1])
    .quad Animal_speak   # vtable[0]: Animal_speak

    .globl _ZTI6Animal
    .align 8
_ZTI6Animal:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Animal                 # type name string
    .quad 0                    # no base class


    .section .rodata
.Ltype_name_Puppy2:
    .string "Puppy2"           # type name
.Ltype_name_Puppy:
    .string "Puppy"           # type name
.Ltype_name_Cat:
    .string "Cat"           # type name
.Ltype_name_Dog:
    .string "Dog"           # type name
.Ltype_name_Animal:
    .string "Animal"           # type name
