# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl add
    add:
    # Function: add (params: 2)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)    # param: a
    movq %rsi, -16(%rbp)    # param: b
    # return expr
    # binary expr
    movq -8(%rbp), %rax    # load a
    pushq %rax
    movq -16(%rbp), %rax    # load b
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    leave
    ret
    leave
    ret
    
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    # var result = ...
    # function call
    movq $1, %rax           # int literal
    pushq %rax
    movq $2, %rax           # int literal
    pushq %rax
    popq %rsi
    popq %rdi
    callq add               # function call
    movq %rax, -16(%rbp)    # store to result
    # return expr
    movq $0, %rax           # int literal
    leave
    ret
    leave
    ret
    
