# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    # var r1 = ...
    # function call
    movq $1, %rax           # int literal
    pushq %rax
    movq $2, %rax           # int literal
    pushq %rax
    popq %rsi
    popq %rdi
    callq _Z3mixIiiE               # function call
    movq %rax, -16(%rbp)    # store to r1
    # var r2 = ...
    # function call
    movq $3, %rax           # int literal
    pushq %rax
    movq $4, %rax           # int literal
    pushq %rax
    popq %rsi
    popq %rdi
    callq _Z3mixIiiE               # function call
    movq %rax, -24(%rbp)    # store to r2
    # return expr
    # binary expr
    # binary expr
    movq -16(%rbp), %rax    # load r1
    pushq %rax
    movq -24(%rbp), %rax    # load r2
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    pushq %rax
    movq $4, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    subq %rcx, %rax              # -
    leave
    ret
    leave
    ret
    
        .globl _Z3mixIiiE
    _Z3mixIiiE:
    # Function: mix (params: 2)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)    # param: a
    movq %rsi, -16(%rbp)    # param: b
    # return expr
    movq -8(%rbp), %rax    # load a
    leave
    ret
    leave
    ret
    
