# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl add             # 导出函数符号，使链接器可见
    add:                       # 函数入口标签
    # Function: add (params: 2)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 形参 a 从寄存器 spill 到栈
    movq %rsi, -16(%rbp)         # 形参 b 从寄存器 spill 到栈
    # return expr
    # binary expr
    movq -8(%rbp), %rax    # 加载局部变量 a 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq -16(%rbp), %rax    # 加载局部变量 b 到 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl main             # 导出函数符号，使链接器可见
    main:                       # 函数入口标签
    # Function: main (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    # var result = ...
    # function call
    movq $1, %rax           # 整数字面量载入 rax
    pushq %rax                  # 实参值压栈暂存
    movq $2, %rax           # 整数字面量载入 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rsi                   # 逆序弹出实参到寄存器
    popq %rdi                   # 逆序弹出实参到寄存器
    callq add                  # 调用函数 add
    movq %rax, -16(%rbp)       # 存储到局部变量 result
    # return expr
    movq -16(%rbp), %rax    # 加载局部变量 result 到 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
