# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    # var a = ...
    movq $35, %rax           # int literal
    movq %rax, -16(%rbp)    # store to a
    # var r1 = ...
    # function call
    movq -16(%rbp), %rax    # load a
    pushq %rax
    popq %rdi
    callq _Z4echoIiE               # function call
    movq %rax, -24(%rbp)    # store to r1
    # var r2 = ...
    # function call
    movq -16(%rbp), %rax    # load a
    pushq %rax
    popq %rdi
    callq _Z3tagIiE               # function call
    movq %rax, -32(%rbp)    # store to r2
    # var r3 = ...
    # function call
    movq $0, %rax           # int literal
    pushq %rax
    popq %rdi
    callq _Z3fwdIiE               # function call
    movq %rax, -40(%rbp)    # store to r3
    # return expr
    # binary expr
    # binary expr
    # binary expr
    movq -24(%rbp), %rax    # load r1
    pushq %rax
    movq -32(%rbp), %rax    # load r2
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    pushq %rax
    movq -40(%rbp), %rax    # load r3
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    pushq %rax
    movq $42, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    subq %rcx, %rax              # -
    leave
    ret
    leave
    ret
    
        .globl _Z4echoIiE
    _Z4echoIiE:
    # Function: echo (params: 1)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)    # param: x
    # return expr
    movq -8(%rbp), %rax    # load x
    leave
    ret
    leave
    ret
    
        .globl _Z3tagIiE
    _Z3tagIiE:
    # Function: tag (params: 1)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)    # param: v
    # return expr
    movq $7, %rax           # int literal
    leave
    ret
    leave
    ret
    
        .globl _Z3fwdIiE
    _Z3fwdIiE:
    # Function: fwd (params: 1)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)    # param: x
    # return expr
    movq -8(%rbp), %rax    # load x
    leave
    ret
    leave
    ret
    
