# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    # var x = ...
    movq $42, %rax           # int literal
    movq %rax, -16(%rbp)    # store to x
    # return expr
    movq $0, %rax           # int literal
    leave
    ret
    leave
    ret
    
