# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl main             # 导出函数符号，使链接器可见
    main:                       # 函数入口标签
    # Function: main (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    # stack object m : MyPtr_int (8 bytes, RAII)
    movq $0, -16(%rbp)    # 零初始化 m 偏移 +0
    movq $7, %rax           # 整数字面量载入 rax
    pushq %rax                  # 构造实参压栈暂存
    popq %rsi                   # 逆序弹出实参到寄存器
    leaq -16(%rbp), %rdi       # this = 栈对象地址 &m
    callq MyPtr_int_MyPtr_int_1               # 调用构造函数（带参重载）
    # if condition
    # binary expr
    # member access: .value
    leaq -16(%rbp), %rax    # 取栈对象地址 &m
    movl 0(%rax), %eax    # 读取字段 .value（偏移 +0，4B int）
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $7, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_1                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $91, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_1:                        # endif 标签
    # stack object b : Box_int (8 bytes, RAII)
    movq $0, -24(%rbp)    # 零初始化 b 偏移 +0
    movq $8, %rax           # 整数字面量载入 rax
    pushq %rax                  # 构造实参压栈暂存
    popq %rsi                   # 逆序弹出实参到寄存器
    leaq -24(%rbp), %rdi       # this = 栈对象地址 &b
    callq Box_int_Box_int_1               # 调用构造函数（带参重载）
    # if condition
    # binary expr
    # member access: .value
    leaq -24(%rbp), %rax    # 取栈对象地址 &b
    movl 0(%rax), %eax    # 读取字段 .value（偏移 +0，4B int）
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $8, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_3                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $92, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_3:                        # endif 标签
    # stack object t : Two_int_int (8 bytes, RAII)
    movq $0, -32(%rbp)    # 零初始化 t 偏移 +0
    movq $9, %rax           # 整数字面量载入 rax
    pushq %rax                  # 构造实参压栈暂存
    popq %rsi                   # 逆序弹出实参到寄存器
    leaq -32(%rbp), %rdi       # this = 栈对象地址 &t
    callq Two_int_int_Two_int_int_1               # 调用构造函数（带参重载）
    movq $10, %rax           # 整数字面量载入 rax
    # member assign: .b = ...
    leaq -32(%rbp), %rax    # 取栈对象地址 &t
    movq %rax, %rcx                # 对象地址存入 rcx
    movq $10, %rax           # 整数字面量载入 rax
    movl %eax, 4(%rcx)    # 写入字段 .b（偏移 +4）
    # if condition
    # binary expr
    # member access: .a
    leaq -32(%rbp), %rax    # 取栈对象地址 &t
    movl 0(%rax), %eax    # 读取字段 .a（偏移 +0，4B int）
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $9, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_5                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $93, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_5:                        # endif 标签
    # if condition
    # binary expr
    # member access: .b
    leaq -32(%rbp), %rax    # 取栈对象地址 &t
    movl 4(%rax), %eax    # 读取字段 .b（偏移 +4，4B int）
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $10, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_7                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $94, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_7:                        # endif 标签
    # var r = ...
    # function call
    leaq -16(%rbp), %rax    # 取栈对象地址 &m
    pushq %rax                  # 实参值压栈暂存
    popq %rdi                   # 逆序弹出实参到寄存器
    callq _Z6readOfIiE                  # 调用函数 _Z6readOfIiE
    movq %rax, -40(%rbp)       # 存储到局部变量 r
    # if condition
    # binary expr
    movq -40(%rbp), %rax    # 加载局部变量 r 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $7, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_9                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $95, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_9:                        # endif 标签
    # stack object explicitOne : MyPtr_int (8 bytes, RAII)
    movq $0, -48(%rbp)    # 零初始化 explicitOne 偏移 +0
    movq $11, %rax           # 整数字面量载入 rax
    pushq %rax                  # 构造实参压栈暂存
    popq %rsi                   # 逆序弹出实参到寄存器
    leaq -48(%rbp), %rdi       # this = 栈对象地址 &explicitOne
    callq MyPtr_int_MyPtr_int_1               # 调用构造函数（带参重载）
    # if condition
    # binary expr
    # member access: .value
    leaq -48(%rbp), %rax    # 取栈对象地址 &explicitOne
    movl 0(%rax), %eax    # 读取字段 .value（偏移 +0，4B int）
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $11, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_11                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $96, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_11:                        # endif 标签
    # return expr
    # binary expr
    # binary expr
    # binary expr
    # binary expr
    # binary expr
    # member access: .a
    leaq -32(%rbp), %rax    # 取栈对象地址 &t
    movl 0(%rax), %eax    # 读取字段 .a（偏移 +0，4B int）
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    # member access: .b
    leaq -32(%rbp), %rax    # 取栈对象地址 &t
    movl 4(%rax), %eax    # 读取字段 .b（偏移 +4，4B int）
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    # member access: .value
    leaq -16(%rbp), %rax    # 取栈对象地址 &m
    movl 0(%rax), %eax    # 读取字段 .value（偏移 +0，4B int）
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    # member access: .value
    leaq -24(%rbp), %rax    # 取栈对象地址 &b
    movl 0(%rax), %eax    # 读取字段 .value（偏移 +0，4B int）
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq -40(%rbp), %rax    # 加载局部变量 r 到 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $132, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    # ~MyPtr_int() auto at function end (RAII)
    leaq -48(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq MyPtr_int_dtor            # 静态调用析构函数（非虚析构路径）
    # ~Two_int_int() auto at function end (RAII)
    leaq -32(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Two_int_int_dtor            # 静态调用析构函数（非虚析构路径）
    # ~Box_int() auto at function end (RAII)
    leaq -24(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Box_int_dtor            # 静态调用析构函数（非虚析构路径）
    # ~MyPtr_int() auto at function end (RAII)
    leaq -16(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq MyPtr_int_dtor            # 静态调用析构函数（非虚析构路径）
    
        .globl MyPtr_int_MyPtr_int_1             # 导出函数符号，使链接器可见
    MyPtr_int_MyPtr_int_1:                       # 函数入口标签
    # Function: MyPtr_int (params: 1)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq %rsi, -16(%rbp)         # 形参 q 从寄存器 spill 到栈
    movq -16(%rbp), %rax    # 加载局部变量 q 到 rax
    movq -8(%rbp), %rcx       # 加载 this 指针
    movl %eax, 0(%rcx)    # 初始化字段 value（偏移 0，4B）
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl MyPtr_int_dtor             # 导出函数符号，使链接器可见
    MyPtr_int_dtor:                       # 函数入口标签
    # Function: ~MyPtr_int (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Box_int_Box_int_1             # 导出函数符号，使链接器可见
    Box_int_Box_int_1:                       # 函数入口标签
    # Function: Box_int (params: 1)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq %rsi, -16(%rbp)         # 形参 q 从寄存器 spill 到栈
    movq -16(%rbp), %rax    # 加载局部变量 q 到 rax
    movq -8(%rbp), %rcx       # 加载 this 指针
    movl %eax, 0(%rcx)    # 初始化字段 value（偏移 0，4B）
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Box_int_dtor             # 导出函数符号，使链接器可见
    Box_int_dtor:                       # 函数入口标签
    # Function: ~Box_int (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Two_int_int_Two_int_int_1             # 导出函数符号，使链接器可见
    Two_int_int_Two_int_int_1:                       # 函数入口标签
    # Function: Two_int_int (params: 1)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq %rsi, -16(%rbp)         # 形参 x 从寄存器 spill 到栈
    movq -16(%rbp), %rax    # 加载局部变量 x 到 rax
    movq -8(%rbp), %rcx       # 加载 this 指针
    movl %eax, 0(%rcx)    # 初始化字段 a（偏移 0，4B）
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Two_int_int_dtor             # 导出函数符号，使链接器可见
    Two_int_int_dtor:                       # 函数入口标签
    # Function: ~Two_int_int (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl _Z6readOfIiE             # 导出函数符号，使链接器可见
    _Z6readOfIiE:                       # 函数入口标签
    # Function: readOf (params: 1)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 形参 p 从寄存器 spill 到栈
    # return expr
    # member access: .value
    movq -8(%rbp), %rax    # 加载局部变量 p 到 rax
    movl 0(%rax), %eax    # 读取字段 .value（偏移 +0，4B int）
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
