# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl main             # 导出函数符号，使链接器可见
    main:                       # 函数入口标签
    # Function: main (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $128, %rsp              # 预留局部变量栈空间（16B 对齐）
    # var a = ...
    movq $1, %rax           # 整数字面量载入 rax
    movq %rax, -16(%rbp)       # 存储到局部变量 a
    # var ra = ...
    movq -16(%rbp), %rax    # 加载局部变量 a 到 rax
    movq %rax, -24(%rbp)       # 存储到局部变量 ra
    # var rr = ...
    movq $2, %rax           # 整数字面量载入 rax
    movq %rax, -32(%rbp)       # 存储到局部变量 rr
    # var p1 = ...
    xorq %rax, %rax             # nullptr = 0（x86 惯用自异或清零）
    movq %rax, -40(%rbp)       # 存储到局部变量 p1
    # var p2 = ...
    xorq %rax, %rax             # nullptr = 0（x86 惯用自异或清零）
    movq %rax, -48(%rbp)       # 存储到局部变量 p2
    # var p3 = ...
    xorq %rax, %rax             # nullptr = 0（x86 惯用自异或清零）
    movq %rax, -56(%rbp)       # 存储到局部变量 p3
    # var p4 = ...
    xorq %rax, %rax             # nullptr = 0（x86 惯用自异或清零）
    movq %rax, -64(%rbp)       # 存储到局部变量 p4
    # stack object t1 : RefKind_intR (8 bytes, RAII)
    movq $0, -72(%rbp)    # 零初始化 t1 偏移 +0
    leaq -72(%rbp), %rdi       # this = 栈对象地址 &t1
    callq RefKind_intR_RefKind_intR               # 调用构造函数
    # stack object t2 : RefKind_intR (8 bytes, RAII)
    movq $0, -80(%rbp)    # 零初始化 t2 偏移 +0
    leaq -80(%rbp), %rdi       # this = 栈对象地址 &t2
    callq RefKind_intR_RefKind_intR               # 调用构造函数
    # stack object t3 : RefKind_intR (8 bytes, RAII)
    movq $0, -88(%rbp)    # 零初始化 t3 偏移 +0
    leaq -88(%rbp), %rdi       # this = 栈对象地址 &t3
    callq RefKind_intR_RefKind_intR               # 调用构造函数
    # stack object t4 : RefKind_intRR (8 bytes, RAII)
    movq $0, -96(%rbp)    # 零初始化 t4 偏移 +0
    leaq -96(%rbp), %rdi       # this = 栈对象地址 &t4
    callq RefKind_intRR_RefKind_intRR               # 调用构造函数
    # if condition
    # binary expr
    # function call
    leaq -72(%rbp), %rax    # 取栈对象地址 &t1
    pushq %rax                   # 暂存 this 指针到栈上
    popq %rdi                   # 弹出 this 指针到 rdi（第 0 参数）
    callq RefKind_intR_v                  # 调用方法 RefKind_intR_v
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $1, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_1                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $11, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_1:                        # endif 标签
    # if condition
    # binary expr
    # function call
    leaq -80(%rbp), %rax    # 取栈对象地址 &t2
    pushq %rax                   # 暂存 this 指针到栈上
    popq %rdi                   # 弹出 this 指针到 rdi（第 0 参数）
    callq RefKind_intR_v                  # 调用方法 RefKind_intR_v
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $1, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_3                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $12, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_3:                        # endif 标签
    # if condition
    # binary expr
    # function call
    leaq -88(%rbp), %rax    # 取栈对象地址 &t3
    pushq %rax                   # 暂存 this 指针到栈上
    popq %rdi                   # 弹出 this 指针到 rdi（第 0 参数）
    callq RefKind_intR_v                  # 调用方法 RefKind_intR_v
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $1, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_5                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $13, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_5:                        # endif 标签
    # if condition
    # binary expr
    # function call
    leaq -96(%rbp), %rax    # 取栈对象地址 &t4
    pushq %rax                   # 暂存 this 指针到栈上
    popq %rdi                   # 弹出 this 指针到 rdi（第 0 参数）
    callq RefKind_intRR_v                  # 调用方法 RefKind_intRR_v
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $2, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_7                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $14, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_7:                        # endif 标签
    # var d1 = ...
    # function call
    movq -16(%rbp), %rax    # 加载局部变量 a 到 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rdi                   # 逆序弹出实参到寄存器
    callq _Z11deduce_kindIRiE                  # 调用函数 _Z11deduce_kindIRiE
    movq %rax, -104(%rbp)       # 存储到局部变量 d1
    # var d2 = ...
    # function call
    movq -24(%rbp), %rax    # 加载局部变量 ra 到 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rdi                   # 逆序弹出实参到寄存器
    callq _Z11deduce_kindIRiE                  # 调用函数 _Z11deduce_kindIRiE
    movq %rax, -112(%rbp)       # 存储到局部变量 d2
    # var d3 = ...
    # function call
    movq -32(%rbp), %rax    # 加载局部变量 rr 到 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rdi                   # 逆序弹出实参到寄存器
    callq _Z11deduce_kindIRiE                  # 调用函数 _Z11deduce_kindIRiE
    movq %rax, -120(%rbp)       # 存储到局部变量 d3
    # var d4 = ...
    # function call
    movq $7, %rax           # 整数字面量载入 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rdi                   # 逆序弹出实参到寄存器
    callq _Z11deduce_kindIiE                  # 调用函数 _Z11deduce_kindIiE
    movq %rax, -128(%rbp)       # 存储到局部变量 d4
    # if condition
    # binary expr
    movq -104(%rbp), %rax    # 加载局部变量 d1 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $1, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_9                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $21, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_9:                        # endif 标签
    # if condition
    # binary expr
    movq -112(%rbp), %rax    # 加载局部变量 d2 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $1, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_11                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $22, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_11:                        # endif 标签
    # if condition
    # binary expr
    movq -120(%rbp), %rax    # 加载局部变量 d3 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $1, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_13                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $23, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_13:                        # endif 标签
    # if condition
    # binary expr
    movq -128(%rbp), %rax    # 加载局部变量 d4 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $0, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_15                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $24, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_15:                        # endif 标签
    # return expr
    movq $0, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    # ~RefKind_intRR() auto at function end (RAII)
    leaq -96(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq RefKind_intRR_dtor            # 静态调用析构函数（非虚析构路径）
    # ~RefKind_intR() auto at function end (RAII)
    leaq -88(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq RefKind_intR_dtor            # 静态调用析构函数（非虚析构路径）
    # ~RefKind_intR() auto at function end (RAII)
    leaq -80(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq RefKind_intR_dtor            # 静态调用析构函数（非虚析构路径）
    # ~RefKind_intR() auto at function end (RAII)
    leaq -72(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq RefKind_intR_dtor            # 静态调用析构函数（非虚析构路径）
    
        .globl LRefHolder_intR_LRefHolder_intR             # 导出函数符号，使链接器可见
    LRefHolder_intR_LRefHolder_intR:                       # 函数入口标签
    # Function: LRefHolder_intR (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl LRefHolder_intR_dtor             # 导出函数符号，使链接器可见
    LRefHolder_intR_dtor:                       # 函数入口标签
    # Function: ~LRefHolder_intR (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl LRefHolder_intRR_LRefHolder_intRR             # 导出函数符号，使链接器可见
    LRefHolder_intRR_LRefHolder_intRR:                       # 函数入口标签
    # Function: LRefHolder_intRR (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl LRefHolder_intRR_dtor             # 导出函数符号，使链接器可见
    LRefHolder_intRR_dtor:                       # 函数入口标签
    # Function: ~LRefHolder_intRR (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl RRefHolder_intR_RRefHolder_intR             # 导出函数符号，使链接器可见
    RRefHolder_intR_RRefHolder_intR:                       # 函数入口标签
    # Function: RRefHolder_intR (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl RRefHolder_intR_dtor             # 导出函数符号，使链接器可见
    RRefHolder_intR_dtor:                       # 函数入口标签
    # Function: ~RRefHolder_intR (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl RRefHolder_intRR_RRefHolder_intRR             # 导出函数符号，使链接器可见
    RRefHolder_intRR_RRefHolder_intRR:                       # 函数入口标签
    # Function: RRefHolder_intRR (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl RRefHolder_intRR_dtor             # 导出函数符号，使链接器可见
    RRefHolder_intRR_dtor:                       # 函数入口标签
    # Function: ~RRefHolder_intRR (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl RefKind_intR_v             # 导出函数符号，使链接器可见
    RefKind_intR_v:                       # 函数入口标签
    # Function: v (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # stack object i : IsRef_int (8 bytes, RAII)
    movq $0, -24(%rbp)    # 零初始化 i 偏移 +0
    leaq -24(%rbp), %rdi       # this = 栈对象地址 &i
    callq IsRef_int_IsRef_int               # 调用构造函数
    # if condition
    # binary expr
    # function call
    leaq -24(%rbp), %rax    # 取栈对象地址 &i
    pushq %rax                   # 暂存 this 指针到栈上
    popq %rdi                   # 弹出 this 指针到 rdi（第 0 参数）
    callq IsRef_int_v                  # 调用方法 IsRef_int_v
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $0, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    sete %al                    # 相等时 al = 1（ZF=1）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_17                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $1, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_17:                        # endif 标签
    # return expr
    movq $9, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    # ~IsRef_int() auto at function end (RAII)
    leaq -24(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq IsRef_int_dtor            # 静态调用析构函数（非虚析构路径）
    
        .globl RefKind_intR_RefKind_intR             # 导出函数符号，使链接器可见
    RefKind_intR_RefKind_intR:                       # 函数入口标签
    # Function: RefKind_intR (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl RefKind_intR_dtor             # 导出函数符号，使链接器可见
    RefKind_intR_dtor:                       # 函数入口标签
    # Function: ~RefKind_intR (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl IsRef_int_v             # 导出函数符号，使链接器可见
    IsRef_int_v:                       # 函数入口标签
    # Function: v (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq $0, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl IsRef_int_IsRef_int             # 导出函数符号，使链接器可见
    IsRef_int_IsRef_int:                       # 函数入口标签
    # Function: IsRef_int (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl IsRef_int_dtor             # 导出函数符号，使链接器可见
    IsRef_int_dtor:                       # 函数入口标签
    # Function: ~IsRef_int (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl RefKind_intRR_v             # 导出函数符号，使链接器可见
    RefKind_intRR_v:                       # 函数入口标签
    # Function: v (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # stack object i : IsRef_int (8 bytes, RAII)
    movq $0, -24(%rbp)    # 零初始化 i 偏移 +0
    leaq -24(%rbp), %rdi       # this = 栈对象地址 &i
    callq IsRef_int_IsRef_int               # 调用构造函数
    # if condition
    # binary expr
    # function call
    leaq -24(%rbp), %rax    # 取栈对象地址 &i
    pushq %rax                   # 暂存 this 指针到栈上
    popq %rdi                   # 弹出 this 指针到 rdi（第 0 参数）
    callq IsRef_int_v                  # 调用方法 IsRef_int_v
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $0, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    sete %al                    # 相等时 al = 1（ZF=1）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_19                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $2, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_19:                        # endif 标签
    # return expr
    movq $9, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    # ~IsRef_int() auto at function end (RAII)
    leaq -24(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq IsRef_int_dtor            # 静态调用析构函数（非虚析构路径）
    
        .globl RefKind_intRR_RefKind_intRR             # 导出函数符号，使链接器可见
    RefKind_intRR_RefKind_intRR:                       # 函数入口标签
    # Function: RefKind_intRR (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl RefKind_intRR_dtor             # 导出函数符号，使链接器可见
    RefKind_intRR_dtor:                       # 函数入口标签
    # Function: ~RefKind_intRR (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl _Z11deduce_kindIRiE             # 导出函数符号，使链接器可见
    _Z11deduce_kindIRiE:                       # 函数入口标签
    # Function: deduce_kind (params: 1)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 形参 x 从寄存器 spill 到栈
    # stack object k : RefKind_intR (8 bytes, RAII)
    movq $0, -24(%rbp)    # 零初始化 k 偏移 +0
    leaq -24(%rbp), %rdi       # this = 栈对象地址 &k
    callq RefKind_intR_RefKind_intR               # 调用构造函数
    # return expr
    # function call
    leaq -24(%rbp), %rax    # 取栈对象地址 &k
    pushq %rax                   # 暂存 this 指针到栈上
    popq %rdi                   # 弹出 this 指针到 rdi（第 0 参数）
    callq RefKind_intR_v                  # 调用方法 RefKind_intR_v
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    # ~RefKind_intR() auto at function end (RAII)
    leaq -24(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq RefKind_intR_dtor            # 静态调用析构函数（非虚析构路径）
    
        .globl _Z11deduce_kindIiE             # 导出函数符号，使链接器可见
    _Z11deduce_kindIiE:                       # 函数入口标签
    # Function: deduce_kind (params: 1)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 形参 x 从寄存器 spill 到栈
    # stack object k : RefKind_int (8 bytes, RAII)
    movq $0, -24(%rbp)    # 零初始化 k 偏移 +0
    leaq -24(%rbp), %rdi       # this = 栈对象地址 &k
    callq RefKind_int_RefKind_int               # 调用构造函数
    # return expr
    # function call
    leaq -24(%rbp), %rax    # 取栈对象地址 &k
    pushq %rax                   # 暂存 this 指针到栈上
    popq %rdi                   # 弹出 this 指针到 rdi（第 0 参数）
    callq RefKind_int_v                  # 调用方法 RefKind_int_v
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    # ~RefKind_int() auto at function end (RAII)
    leaq -24(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq RefKind_int_dtor            # 静态调用析构函数（非虚析构路径）
    
        .globl RefKind_int_v             # 导出函数符号，使链接器可见
    RefKind_int_v:                       # 函数入口标签
    # Function: v (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq $0, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl RefKind_int_RefKind_int             # 导出函数符号，使链接器可见
    RefKind_int_RefKind_int:                       # 函数入口标签
    # Function: RefKind_int (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl RefKind_int_dtor             # 导出函数符号，使链接器可见
    RefKind_int_dtor:                       # 函数入口标签
    # Function: ~RefKind_int (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
