# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl twice
    twice:
    # Function: twice (params: 1)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)    # param: x
    # return expr
    # binary expr
    movq -8(%rbp), %rax    # load x
    pushq %rax
    movq $3, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    imulq %rcx, %rax             # *
    leave
    ret
    leave
    ret
    
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    # var r = ...
    # function call
    movq $2, %rax           # int literal
    pushq %rax
    popq %rdi
    callq twice               # function call
    movq %rax, -16(%rbp)    # store to r
    # function call
    xorq %rax, %rax                # nullptr = 0
    pushq %rax
    popq %rdi
    callq _Z2poIvE               # function call
    # return expr
    # binary expr
    movq -16(%rbp), %rax    # load r
    pushq %rax
    movq $6, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    subq %rcx, %rax              # -
    leave
    ret
    leave
    ret
    
        .globl _Z2poIvE
    _Z2poIvE:
    # Function: po (params: 1)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)    # param: x
    movq $0, %rax
    leave
    ret
    
