
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/local/lib/python3.9/dist-packages/cmake/data/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/root/.local/bin/"
      - "/root/bin/"
      - "/root/.fzf/bin/"
      - "/root/devtools/vcpkg/"
      - "/root/.tiup/bin/"
      - "/root/.krew/bin/"
      - "/root/.sdkman/candidates/java/current/bin/"
      - "/usr/local/go/bin/"
      - "/root/gobin/"
      - "/root/.nvm/versions/node/v20.20.2/bin/"
      - "/root/proto/bin/"
      - "/home/magene/apache-maven-3.8.1/bin/"
      - "/home/magene/runtime/cppproject/mycompiler/build-linux/_deps/googletest-subbuild/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/root/.platformio/penv/bin/"
    searched_directories:
      - "/root/.local/bin/uname"
      - "/root/bin/uname"
      - "/root/.fzf/bin/uname"
      - "/root/devtools/vcpkg/uname"
      - "/root/.tiup/bin/uname"
      - "/root/.krew/bin/uname"
      - "/root/.sdkman/candidates/java/current/bin/uname"
      - "/usr/local/go/bin/uname"
      - "/root/gobin/uname"
      - "/root/.nvm/versions/node/v20.20.2/bin/uname"
      - "/root/proto/bin/uname"
      - "/home/magene/apache-maven-3.8.1/bin/uname"
      - "/home/magene/runtime/cppproject/mycompiler/build-linux/_deps/googletest-subbuild/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/root/.local/bin"
        - "/root/bin"
        - "/root/.fzf/bin"
        - "/root/devtools/vcpkg"
        - "/root/.tiup/bin"
        - "/root/.krew/bin"
        - "/root/.sdkman/candidates/java/current/bin"
        - "/usr/local/go/bin"
        - "/root/gobin"
        - "/root/.nvm/versions/node/v20.20.2/bin"
        - "/root/proto/bin"
        - "/home/magene/apache-maven-3.8.1/bin"
        - "."
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/root/.platformio/penv/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/lib/python3.9/dist-packages/cmake/data/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.10.0-20-amd64 - x86_64
...
