# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl add             # 导出函数符号，使链接器可见
    add:                       # 函数入口标签
    # Function: add (params: 2)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 形参 a 从寄存器 spill 到栈
    movq %rsi, -16(%rbp)         # 形参 b 从寄存器 spill 到栈
    # var result = ...
    # binary expr
    movq -8(%rbp), %rax    # 加载局部变量 a 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq -16(%rbp), %rax    # 加载局部变量 b 到 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    movq %rax, -32(%rbp)       # 存储到局部变量 result
    # return expr
    movq -32(%rbp), %rax    # 加载局部变量 result 到 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl factorial             # 导出函数符号，使链接器可见
    factorial:                       # 函数入口标签
    # Function: factorial (params: 1)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 形参 n 从寄存器 spill 到栈
    # if condition
    # binary expr
    movq -8(%rbp), %rax    # 加载局部变量 n 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $1, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setle %al                   # 小于等于时 al = 1（ZF=1 或 SF≠OF）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_1                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $1, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_1:                        # endif 标签
    # return expr
    # binary expr
    movq -8(%rbp), %rax    # 加载局部变量 n 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    # function call
    # binary expr
    movq -8(%rbp), %rax    # 加载局部变量 n 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $1, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    subq %rcx, %rax             # 减法：rax = rax - rcx
    pushq %rax                  # 实参值压栈暂存
    popq %rdi                   # 逆序弹出实参到寄存器
    callq factorial                  # 调用函数 factorial
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    imulq %rcx, %rax            # 乘法：rax = rax * rcx（有符号）
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl testAutoChain             # 导出函数符号，使链接器可见
    testAutoChain:                       # 函数入口标签
    # Function: testAutoChain (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    # var x = ...
    movq $10, %rax           # 整数字面量载入 rax
    movq %rax, -16(%rbp)       # 存储到局部变量 x
    # var y = ...
    # binary expr
    movq -16(%rbp), %rax    # 加载局部变量 x 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $20, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    movq %rax, -24(%rbp)       # 存储到局部变量 y
    # var z = ...
    # binary expr
    movq -24(%rbp), %rax    # 加载局部变量 y 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq -16(%rbp), %rax    # 加载局部变量 x 到 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    imulq %rcx, %rax            # 乘法：rax = rax * rcx（有符号）
    movq %rax, -32(%rbp)       # 存储到局部变量 z
    # var flag = ...
    # binary expr
    movq -32(%rbp), %rax    # 加载局部变量 z 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $100, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setg %al                    # 大于时 al = 1（ZF=0 且 SF=OF）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    movq %rax, -40(%rbp)       # 存储到局部变量 flag
    # return expr
    movq -32(%rbp), %rax    # 加载局部变量 z 到 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Animal_speak             # 导出函数符号，使链接器可见
    Animal_speak:                       # 函数入口标签
    # Function: speak (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq $0, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Animal_Animal             # 导出函数符号，使链接器可见
    Animal_Animal:                       # 函数入口标签
    # Function: Animal (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV6Animal(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Animal_dtor             # 导出函数符号，使链接器可见
    Animal_dtor:                       # 函数入口标签
    # Function: ~Animal (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Dog_speak             # 导出函数符号，使链接器可见
    Dog_speak:                       # 函数入口标签
    # Function: speak (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq $1, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Dog_Dog             # 导出函数符号，使链接器可见
    Dog_Dog:                       # 函数入口标签
    # Function: Dog (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV3Dog(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Dog_dtor             # 导出函数符号，使链接器可见
    Dog_dtor:                       # 函数入口标签
    # Function: ~Dog (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl testPoly             # 导出函数符号，使链接器可见
    testPoly:                       # 函数入口标签
    # Function: testPoly (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    # var pet = ...
    # new Dog()
    movq $24, %rdi             # malloc 分配大小：24 字节
    callq malloc                  # 调用 malloc 分配堆内存
    pushq %rax                    # 暂存返回的对象指针到栈上
    leaq _ZTV3Dog(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq (%rsp), %rax           # 从栈上取回对象指针
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq (%rsp), %rdi             # this = 已分配对象指针（栈顶取出）
    callq Dog_Dog                 # 调用构造函数 Dog_Dog
    popq %rax                     # 弹出对象指针作为 new 表达式返回值
    # end new Dog()
    movq %rax, -16(%rbp)       # 存储到局部变量 pet
    # var voice = ...
    # function call
    movq -16(%rbp), %rax    # 加载局部变量 pet 到 rax
    movq %rax, %rdi            # this = 对象地址（第 0 参数）
    # VIRTUAL CALL: Animal::speak (vtable[0])
    pushq %rdi                   # 暂存 this（对象地址）到栈上保护
    popq %rdi                   # 弹出 this 指针（恢复对象地址）
    # ═══ 虚函数调用 (a)：从对象读出 _vptr ═══
    movq (%rdi), %rax            # 从对象首 8 字节读出 _vptr
    # ═══ 虚函数调用 (b)：从 vtable 加载函数地址 ═══
    movq 0(%rax), %rax       # 从 vtable[0] 读出函数地址（偏移 0）
    # ═══ 虚函数调用 (c)：间接跳转到真实函数 ═══
    callq *%rax                  # 经 vtable 间接调用（跳转到 rax 所指地址）
    # END VIRTUAL CALL Animal::speak
    movq %rax, -24(%rbp)       # 存储到局部变量 voice
    # return expr
    movq -24(%rbp), %rax    # 加载局部变量 voice 到 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl testFields             # 导出函数符号，使链接器可见
    testFields:                       # 函数入口标签
    # Function: testFields (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    # stack object d : Dog (24 bytes, RAII)
    movq $0, -32(%rbp)    # 零初始化 d 偏移 +0
    movq $0, -24(%rbp)    # 零初始化 d 偏移 +8
    movq $0, -16(%rbp)    # 零初始化 d 偏移 +16
    leaq _ZTV3Dog(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, -32(%rbp)    # 安装主 _vptr 到栈对象
    leaq -32(%rbp), %rdi       # this = 栈对象地址 &d
    callq Dog_Dog               # 调用构造函数
    movq $5, %rax           # 整数字面量载入 rax
    # member assign: .age = ...
    leaq -32(%rbp), %rax    # 取栈对象地址 &d
    movq %rax, %rcx                # 对象地址存入 rcx
    movq $5, %rax           # 整数字面量载入 rax
    movl %eax, 8(%rcx)    # 写入字段 .age（偏移 +8）
    movq $3, %rax           # 整数字面量载入 rax
    # member assign: .tricks = ...
    leaq -32(%rbp), %rax    # 取栈对象地址 &d
    movq %rax, %rcx                # 对象地址存入 rcx
    movq $3, %rax           # 整数字面量载入 rax
    movl %eax, 16(%rcx)    # 写入字段 .tricks（偏移 +16）
    # var total = ...
    # binary expr
    # member access: .age
    leaq -32(%rbp), %rax    # 取栈对象地址 &d
    movl 8(%rax), %eax    # 读取字段 .age（偏移 +8，4B int）
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    # member access: .tricks
    leaq -32(%rbp), %rax    # 取栈对象地址 &d
    movl 16(%rax), %eax    # 读取字段 .tricks（偏移 +16，4B int）
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    movq %rax, -40(%rbp)       # 存储到局部变量 total
    # return expr
    movq -40(%rbp), %rax    # 加载局部变量 total 到 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    # ~Dog() auto at function end (RAII)
    leaq -32(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Dog_dtor            # 静态调用析构函数（非虚析构路径）
    
        .globl main             # 导出函数符号，使链接器可见
    main:                       # 函数入口标签
    # Function: main (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    # var r1 = ...
    # function call
    movq $3, %rax           # 整数字面量载入 rax
    pushq %rax                  # 实参值压栈暂存
    movq $4, %rax           # 整数字面量载入 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rsi                   # 逆序弹出实参到寄存器
    popq %rdi                   # 逆序弹出实参到寄存器
    callq add                  # 调用函数 add
    movq %rax, -16(%rbp)       # 存储到局部变量 r1
    # var r2 = ...
    # function call
    movq $5, %rax           # 整数字面量载入 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rdi                   # 逆序弹出实参到寄存器
    callq factorial                  # 调用函数 factorial
    movq %rax, -24(%rbp)       # 存储到局部变量 r2
    # var r3 = ...
    # function call
    callq testAutoChain                  # 调用函数 testAutoChain
    movq %rax, -32(%rbp)       # 存储到局部变量 r3
    # var r4 = ...
    # function call
    callq testPoly                  # 调用函数 testPoly
    movq %rax, -40(%rbp)       # 存储到局部变量 r4
    # var r5 = ...
    # function call
    callq testFields                  # 调用函数 testFields
    movq %rax, -48(%rbp)       # 存储到局部变量 r5
    # return expr
    movq $0, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    

    .data
    .globl _ZTV6Animal             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV6Animal:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI6Animal       # RTTI type_info 指针（vtable[-1]）
    .quad Animal_speak   # vtable[0]: 虚函数 Animal_speak

    .globl _ZTI6Animal             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI6Animal:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_Animal                 # 指向类型名称字符串
    .quad 0                 # 无基类（基类计数 = 0）

    .globl _ZTV3Dog             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV3Dog:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI3Dog       # RTTI type_info 指针（vtable[-1]）
    .quad Dog_speak   # vtable[0]: 虚函数 Dog_speak

    .globl _ZTI3Dog             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI3Dog:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_Dog                 # 指向类型名称字符串
    .quad 1                 # 基类计数（MI 计数风格）
    .quad _ZTI6Animal                 # base[Animal] typeinfo 指针
    .quad 0                 # base[Animal] 子对象偏移（字节）


    .section .rodata
.Ltype_name_Animal:                     # 类型名称标签
    .string "Animal"           # 类型名称字符串
.Ltype_name_Dog:                     # 类型名称标签
    .string "Dog"           # 类型名称字符串
