# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl add
    add:
    # Function: add (params: 2)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    movq %rdi, -8(%rbp)    # param: a
    movq %rsi, -16(%rbp)    # param: b
    # var result = ...
    # binary expr
    movq -8(%rbp), %rax    # load a
    pushq %rax
    movq -16(%rbp), %rax    # load b
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    movq %rax, -32(%rbp)    # store to result
    # return expr
    movq -32(%rbp), %rax    # load result
    leave
    ret
    leave
    ret
    
        .globl factorial
    factorial:
    # Function: factorial (params: 1)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    movq %rdi, -8(%rbp)    # param: n
    # if condition
    # binary expr
    movq -8(%rbp), %rax    # load n
    pushq %rax
    movq $1, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    cmpq %rcx, %rax
    setle %al                    # <=
    movzbq %al, %rax
    testq %rax, %rax
    je endif_1
    # then branch
    # return expr
    movq $1, %rax           # int literal
    leave
    ret
    endif_1:
    # return expr
    # binary expr
    movq -8(%rbp), %rax    # load n
    pushq %rax
    # function call
    # binary expr
    movq -8(%rbp), %rax    # load n
    pushq %rax
    movq $1, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    subq %rcx, %rax              # -
    pushq %rax
    popq %rdi
    callq factorial               # function call
    movq %rax, %rcx
    popq %rax
    imulq %rcx, %rax             # *
    leave
    ret
    leave
    ret
    
        .globl testAutoChain
    testAutoChain:
    # Function: testAutoChain (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    # var x = ...
    movq $10, %rax           # int literal
    movq %rax, -16(%rbp)    # store to x
    # var y = ...
    # binary expr
    movq -16(%rbp), %rax    # load x
    pushq %rax
    movq $20, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    movq %rax, -24(%rbp)    # store to y
    # var z = ...
    # binary expr
    movq -24(%rbp), %rax    # load y
    pushq %rax
    movq -16(%rbp), %rax    # load x
    movq %rax, %rcx
    popq %rax
    imulq %rcx, %rax             # *
    movq %rax, -32(%rbp)    # store to z
    # var flag = ...
    # binary expr
    movq -32(%rbp), %rax    # load z
    pushq %rax
    movq $100, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    cmpq %rcx, %rax
    setg %al                     # >
    movzbq %al, %rax
    movq %rax, -40(%rbp)    # store to flag
    # return expr
    movq -32(%rbp), %rax    # load z
    leave
    ret
    leave
    ret
    
        .globl Animal_speak
    Animal_speak:
    # Function: speak (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    movq %rdi, -8(%rbp)
    # return expr
    movq $0, %rax           # int literal
    leave
    ret
    leave
    ret
    
        .globl Animal_Animal
    Animal_Animal:
    # Function: Animal (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV6Animal(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Animal_dtor
    Animal_dtor:
    # Function: ~Animal (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl Dog_speak
    Dog_speak:
    # Function: speak (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    movq %rdi, -8(%rbp)
    # return expr
    movq $1, %rax           # int literal
    leave
    ret
    leave
    ret
    
        .globl Dog_Dog
    Dog_Dog:
    # Function: Dog (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV3Dog(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Dog_dtor
    Dog_dtor:
    # Function: ~Dog (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl testPoly
    testPoly:
    # Function: testPoly (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    # var pet = ...
    # new Dog()
    movq $16, %rdi             # malloc size
    callq malloc                  # allocate memory
    pushq %rax                    # save allocated objPtr
    leaq _ZTV3Dog(%rip), %rcx    # vtable address
    addq $16, %rcx              # skip to vtable[0]
    movq (%rsp), %rax           # load objPtr
    movq %rcx, (%rax)           # obj._vptr = vtable
    movq (%rsp), %rdi             # this pointer
    callq Dog_Dog              # call constructor
    popq %rax                     # return objPtr
    # end new Dog()
    movq %rax, -16(%rbp)    # store to pet
    # var voice = ...
    # function call
    # VIRTUAL CALL: Animal::speak (vtable[0])
    movq %rdi, %rbx              # save object pointer
    movq %rbx, %rdi              # this pointer
    # ═══ Virtual Call Step (a): Read _vptr from object ═══
    movq (%rdi), %rax            # rax = obj._vptr (at offset 0)
    # ═══ Virtual Call Step (b): Load function address from vtable ═══
    movq 0(%rax), %rax       # rax = vtable[0] (offset 0)
    # ═══ Virtual Call Step (c): Jump to the real function ═══
    callq *%rax                  # indirect call via vtable
    # END VIRTUAL CALL Animal::speak
    movq %rax, -24(%rbp)    # store to voice
    # return expr
    movq -24(%rbp), %rax    # load voice
    leave
    ret
    leave
    ret
    
        .globl testFields
    testFields:
    # Function: testFields (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    movq $0, -16(%rbp)    # zero init d
    movq $5, %rax           # int literal
    # member assign: .age = ...
    movq -16(%rbp), %rax    # load d
    movq %rax, %rcx                # object address
    movq $5, %rax           # int literal
    movl %eax, 8(%rcx)    # .age (offset 8)
    movq $3, %rax           # int literal
    # member assign: .tricks = ...
    movq -16(%rbp), %rax    # load d
    movq %rax, %rcx                # object address
    movq $3, %rax           # int literal
    movl %eax, 12(%rcx)    # .tricks (offset 12)
    # var total = ...
    # binary expr
    # member access: .age
    movq -16(%rbp), %rax    # load d
    movq 8(%rax), %rax    # .age (offset 8)
    pushq %rax
    # member access: .tricks
    movq -16(%rbp), %rax    # load d
    movq 12(%rax), %rax    # .tricks (offset 12)
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    movq %rax, -24(%rbp)    # store to total
    # return expr
    movq -24(%rbp), %rax    # load total
    leave
    ret
    leave
    ret
    
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    # var r1 = ...
    # function call
    movq $3, %rax           # int literal
    pushq %rax
    movq $4, %rax           # int literal
    pushq %rax
    popq %rsi
    popq %rdi
    callq add               # function call
    movq %rax, -16(%rbp)    # store to r1
    # var r2 = ...
    # function call
    movq $5, %rax           # int literal
    pushq %rax
    popq %rdi
    callq factorial               # function call
    movq %rax, -24(%rbp)    # store to r2
    # var r3 = ...
    # function call
    callq testAutoChain               # function call
    movq %rax, -32(%rbp)    # store to r3
    # var r4 = ...
    # function call
    callq testPoly               # function call
    movq %rax, -40(%rbp)    # store to r4
    # var r5 = ...
    # function call
    callq testFields               # function call
    movq %rax, -48(%rbp)    # store to r5
    # return expr
    movq $0, %rax           # int literal
    leave
    ret
    leave
    ret
    

    .data
    .globl _ZTV3Dog
    .align 8
_ZTV3Dog:
    .quad 0                    # offset to top
    .quad _ZTI3Dog       # RTTI type_info pointer (vtable[-1])
    .quad Dog_speak   # vtable[0]: Dog_speak

    .globl _ZTI3Dog
    .align 8
_ZTI3Dog:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Dog                 # type name string
    .quad _ZTI6Animal                 # base class typeinfo

    .globl _ZTV6Animal
    .align 8
_ZTV6Animal:
    .quad 0                    # offset to top
    .quad _ZTI6Animal       # RTTI type_info pointer (vtable[-1])
    .quad Animal_speak   # vtable[0]: Animal_speak

    .globl _ZTI6Animal
    .align 8
_ZTI6Animal:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Animal                 # type name string
    .quad 0                    # no base class


    .section .rodata
.Ltype_name_Dog:
    .string "Dog"           # type name
.Ltype_name_Animal:
    .string "Animal"           # type name
