# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl Base_f             # 导出函数符号，使链接器可见
    Base_f:                       # 函数入口标签
    # Function: f (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq $1, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Base_f_1             # 导出函数符号，使链接器可见
    Base_f_1:                       # 函数入口标签
    # Function: f (params: 1)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq %rsi, -16(%rbp)         # 形参 x 从寄存器 spill 到栈
    # return expr
    # binary expr
    movq -16(%rbp), %rax    # 加载局部变量 x 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $10, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Base_Base             # 导出函数符号，使链接器可见
    Base_Base:                       # 函数入口标签
    # Function: Base (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV4Base(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Base_dtor             # 导出函数符号，使链接器可见
    Base_dtor:                       # 函数入口标签
    # Function: ~Base (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Derived_f             # 导出函数符号，使链接器可见
    Derived_f:                       # 函数入口标签
    # Function: f (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq $100, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Derived_Derived             # 导出函数符号，使链接器可见
    Derived_Derived:                       # 函数入口标签
    # Function: Derived (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV7Derived(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Derived_dtor             # 导出函数符号，使链接器可见
    Derived_dtor:                       # 函数入口标签
    # Function: ~Derived (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl main             # 导出函数符号，使链接器可见
    main:                       # 函数入口标签
    # Function: main (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    # stack object b : Base (8 bytes, RAII)
    movq $0, -16(%rbp)    # 零初始化 b 偏移 +0
    leaq _ZTV4Base(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, -16(%rbp)    # 安装主 _vptr 到栈对象
    leaq -16(%rbp), %rdi       # this = 栈对象地址 &b
    callq Base_Base               # 调用构造函数
    # if condition
    # binary expr
    # function call
    leaq -16(%rbp), %rax    # 取栈对象地址 &b
    movq %rax, %rdi            # this = 对象地址（第 0 参数）
    # VIRTUAL CALL: Base::f (vtable[0])
    pushq %rdi                   # 暂存 this（对象地址）到栈上保护
    popq %rdi                   # 弹出 this 指针（恢复对象地址）
    # ═══ 虚函数调用 (a)：从对象读出 _vptr ═══
    movq (%rdi), %rax            # 从对象首 8 字节读出 _vptr
    # ═══ 虚函数调用 (b)：从 vtable 加载函数地址 ═══
    movq 0(%rax), %rax       # 从 vtable[0] 读出函数地址（偏移 0）
    # ═══ 虚函数调用 (c)：间接跳转到真实函数 ═══
    callq *%rax                  # 经 vtable 间接调用（跳转到 rax 所指地址）
    # END VIRTUAL CALL Base::f
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $1, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_1                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $1, %rax           # 整数字面量载入 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~Base() before return (RAII, scope exit)
    leaq -16(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Base_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_1:                        # endif 标签
    # if condition
    # binary expr
    # function call
    leaq -16(%rbp), %rax    # 取栈对象地址 &b
    pushq %rax                   # 暂存 this 指针到栈上
    movq $2, %rax           # 整数字面量载入 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rsi                   # 逆序弹出实参到寄存器
    popq %rdi                   # 弹出 this 指针到 rdi（第 0 参数）
    callq Base_f_1                  # 调用方法 Base_f_1
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $12, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_3                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $2, %rax           # 整数字面量载入 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~Base() before return (RAII, scope exit)
    leaq -16(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Base_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_3:                        # endif 标签
    # stack object d : Derived (8 bytes, RAII)
    movq $0, -24(%rbp)    # 零初始化 d 偏移 +0
    leaq _ZTV7Derived(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, -24(%rbp)    # 安装主 _vptr 到栈对象
    leaq -24(%rbp), %rdi       # this = 栈对象地址 &d
    callq Derived_Derived               # 调用构造函数
    # if condition
    # binary expr
    # function call
    leaq -24(%rbp), %rax    # 取栈对象地址 &d
    movq %rax, %rdi            # this = 对象地址（第 0 参数）
    # VIRTUAL CALL: Derived::f (vtable[0])
    pushq %rdi                   # 暂存 this（对象地址）到栈上保护
    popq %rdi                   # 弹出 this 指针（恢复对象地址）
    # ═══ 虚函数调用 (a)：从对象读出 _vptr ═══
    movq (%rdi), %rax            # 从对象首 8 字节读出 _vptr
    # ═══ 虚函数调用 (b)：从 vtable 加载函数地址 ═══
    movq 0(%rax), %rax       # 从 vtable[0] 读出函数地址（偏移 0）
    # ═══ 虚函数调用 (c)：间接跳转到真实函数 ═══
    callq *%rax                  # 经 vtable 间接调用（跳转到 rax 所指地址）
    # END VIRTUAL CALL Derived::f
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $100, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_5                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $3, %rax           # 整数字面量载入 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~Derived() before return (RAII, scope exit)
    leaq -24(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Derived_dtor            # 静态调用析构函数（非虚析构路径）
    # ~Base() before return (RAII, scope exit)
    leaq -16(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Base_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_5:                        # endif 标签
    # var p = ...
    leaq -24(%rbp), %rax    # &d = 栈对象地址
    movq %rax, -32(%rbp)       # 存储到局部变量 p
    # if condition
    # binary expr
    # function call
    movq -32(%rbp), %rax    # 加载局部变量 p 到 rax
    movq %rax, %rdi            # this = 对象地址（第 0 参数）
    # VIRTUAL CALL: Base::f (vtable[0])
    pushq %rdi                   # 暂存 this（对象地址）到栈上保护
    popq %rdi                   # 弹出 this 指针（恢复对象地址）
    # ═══ 虚函数调用 (a)：从对象读出 _vptr ═══
    movq (%rdi), %rax            # 从对象首 8 字节读出 _vptr
    # ═══ 虚函数调用 (b)：从 vtable 加载函数地址 ═══
    movq 0(%rax), %rax       # 从 vtable[0] 读出函数地址（偏移 0）
    # ═══ 虚函数调用 (c)：间接跳转到真实函数 ═══
    callq *%rax                  # 经 vtable 间接调用（跳转到 rax 所指地址）
    # END VIRTUAL CALL Base::f
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $100, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_7                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $4, %rax           # 整数字面量载入 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~Derived() before return (RAII, scope exit)
    leaq -24(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Derived_dtor            # 静态调用析构函数（非虚析构路径）
    # ~Base() before return (RAII, scope exit)
    leaq -16(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Base_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_7:                        # endif 标签
    # return expr
    movq $0, %rax           # 整数字面量载入 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~Derived() before return (RAII, scope exit)
    leaq -24(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Derived_dtor            # 静态调用析构函数（非虚析构路径）
    # ~Base() before return (RAII, scope exit)
    leaq -16(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Base_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    # ~Derived() auto at function end (RAII)
    leaq -24(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Derived_dtor            # 静态调用析构函数（非虚析构路径）
    # ~Base() auto at function end (RAII)
    leaq -16(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Base_dtor            # 静态调用析构函数（非虚析构路径）
    

    .data
    .globl _ZTV7Derived             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV7Derived:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI7Derived       # RTTI type_info 指针（vtable[-1]）
    .quad Derived_f   # vtable[0]: 虚函数 Derived_f

    .globl _ZTI7Derived             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI7Derived:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_Derived                 # 指向类型名称字符串
    .quad 1                 # 基类计数（MI 计数风格）
    .quad _ZTI4Base                 # base[Base] typeinfo 指针
    .quad 0                 # base[Base] 子对象偏移（字节）

    .globl _ZTV4Base             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV4Base:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI4Base       # RTTI type_info 指针（vtable[-1]）
    .quad Base_f   # vtable[0]: 虚函数 Base_f

    .globl _ZTI4Base             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI4Base:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_Base                 # 指向类型名称字符串
    .quad 0                 # 无基类（基类计数 = 0）


    .section .rodata
.Ltype_name_Derived:                     # 类型名称标签
    .string "Derived"           # 类型名称字符串
.Ltype_name_Base:                     # 类型名称标签
    .string "Base"           # 类型名称字符串
