# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl A_g             # 导出函数符号，使链接器可见
    A_g:                       # 函数入口标签
    # Function: g (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq $5, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl A_A             # 导出函数符号，使链接器可见
    A_A:                       # 函数入口标签
    # Function: A (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl A_dtor             # 导出函数符号，使链接器可见
    A_dtor:                       # 函数入口标签
    # Function: ~A (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl B_B             # 导出函数符号，使链接器可见
    B_B:                       # 函数入口标签
    # Function: B (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl B_dtor             # 导出函数符号，使链接器可见
    B_dtor:                       # 函数入口标签
    # Function: ~B (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl C_C             # 导出函数符号，使链接器可见
    C_C:                       # 函数入口标签
    # Function: C (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl C_dtor             # 导出函数符号，使链接器可见
    C_dtor:                       # 函数入口标签
    # Function: ~C (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Base_g             # 导出函数符号，使链接器可见
    Base_g:                       # 函数入口标签
    # Function: g (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq $1, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Base_Base             # 导出函数符号，使链接器可见
    Base_Base:                       # 函数入口标签
    # Function: Base (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Base_dtor             # 导出函数符号，使链接器可见
    Base_dtor:                       # 函数入口标签
    # Function: ~Base (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl D_g             # 导出函数符号，使链接器可见
    D_g:                       # 函数入口标签
    # Function: g (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq $2, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl D_D             # 导出函数符号，使链接器可见
    D_D:                       # 函数入口标签
    # Function: D (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl D_dtor             # 导出函数符号，使链接器可见
    D_dtor:                       # 函数入口标签
    # Function: ~D (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl main             # 导出函数符号，使链接器可见
    main:                       # 函数入口标签
    # Function: main (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    # var p = ...
    # new C()
    movq $8, %rdi             # malloc 分配大小：8 字节
    callq malloc                  # 调用 malloc 分配堆内存
    pushq %rax                    # 暂存返回的对象指针到栈上
    movq (%rsp), %rdi             # this = 已分配对象指针（栈顶取出）
    callq C_C                 # 调用构造函数 C_C
    popq %rax                     # 弹出对象指针作为 new 表达式返回值
    # end new C()
    movq %rax, -16(%rbp)       # 存储到局部变量 p
    # var r = ...
    # function call
    movq -16(%rbp), %rax    # 加载局部变量 p 到 rax
    pushq %rax                   # 暂存 this 指针到栈上
    popq %rdi                   # 弹出 this 指针到 rdi（第 0 参数）
    callq A_g                  # 调用方法 A_g
    movq %rax, -24(%rbp)       # 存储到局部变量 r
    # stack object d : D (8 bytes, RAII)
    movq $0, -32(%rbp)    # 零初始化 d 偏移 +0
    leaq -32(%rbp), %rdi       # this = 栈对象地址 &d
    callq D_D               # 调用构造函数
    # binary expr
    movq -24(%rbp), %rax    # 加载局部变量 r 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    # function call
    leaq -32(%rbp), %rax    # 取栈对象地址 &d
    pushq %rax                   # 暂存 this 指针到栈上
    popq %rdi                   # 弹出 this 指针到 rdi（第 0 参数）
    callq D_g                  # 调用方法 D_g
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    movq %rax, -24(%rbp)       # 赋值局部变量 r
    # stack object b : Base (8 bytes, RAII)
    movq $0, -40(%rbp)    # 零初始化 b 偏移 +0
    leaq -40(%rbp), %rdi       # this = 栈对象地址 &b
    callq Base_Base               # 调用构造函数
    # binary expr
    movq -24(%rbp), %rax    # 加载局部变量 r 到 rax
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    # function call
    leaq -40(%rbp), %rax    # 取栈对象地址 &b
    pushq %rax                   # 暂存 this 指针到栈上
    popq %rdi                   # 弹出 this 指针到 rdi（第 0 参数）
    callq Base_g                  # 调用方法 Base_g
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    movq %rax, -24(%rbp)       # 赋值局部变量 r
    # return expr
    movq -24(%rbp), %rax    # 加载局部变量 r 到 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~Base() before return (RAII, scope exit)
    leaq -40(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Base_dtor            # 静态调用析构函数（非虚析构路径）
    # ~D() before return (RAII, scope exit)
    leaq -32(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq D_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    # ~Base() auto at function end (RAII)
    leaq -40(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Base_dtor            # 静态调用析构函数（非虚析构路径）
    # ~D() auto at function end (RAII)
    leaq -32(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq D_dtor            # 静态调用析构函数（非虚析构路径）
    
