# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl X_f             # 导出函数符号，使链接器可见
    X_f:                       # 函数入口标签
    # Function: f (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq $0, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl X_X             # 导出函数符号，使链接器可见
    X_X:                       # 函数入口标签
    # Function: X (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV1X(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl X_dtor             # 导出函数符号，使链接器可见
    X_dtor:                       # 函数入口标签
    # Function: ~X (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl P_P             # 导出函数符号，使链接器可见
    P_P:                       # 函数入口标签
    # Function: P (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV1P(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl P_dtor             # 导出函数符号，使链接器可见
    P_dtor:                       # 函数入口标签
    # Function: ~P (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Q_Q             # 导出函数符号，使链接器可见
    Q_Q:                       # 函数入口标签
    # Function: Q (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV1Q(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Q_dtor             # 导出函数符号，使链接器可见
    Q_dtor:                       # 函数入口标签
    # Function: ~Q (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Diamond_Diamond             # 导出函数符号，使链接器可见
    Diamond_Diamond:                       # 函数入口标签
    # Function: Diamond (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV7Diamond(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    leaq _ZTV7Diamond(%rip), %rcx    # 取次表首地址（基类 'Q'）
    addq $40, %rcx          # 跳过次表头，指向 secondary[0]
    movq %rcx, 16(%rax)     # 安装次 _vptr（偏移 Q 处）
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Diamond_dtor             # 导出函数符号，使链接器可见
    Diamond_dtor:                       # 函数入口标签
    # Function: ~Diamond (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl main             # 导出函数符号，使链接器可见
    main:                       # 函数入口标签
    # Function: main (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    # var obj = ...
    # new Diamond()
    movq $40, %rdi             # malloc 分配大小：40 字节
    callq malloc                  # 调用 malloc 分配堆内存
    pushq %rax                    # 暂存返回的对象指针到栈上
    leaq _ZTV7Diamond(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq (%rsp), %rax           # 从栈上取回对象指针
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq (%rsp), %rax           # 从栈上取回对象指针
    leaq _ZTV7Diamond(%rip), %rcx    # 取次表首地址（基类 'Q'）
    addq $40, %rcx          # 跳过次表头，指向 secondary[0]
    movq %rcx, 16(%rax)     # 安装次 _vptr（偏移 Q 处）
    movq (%rsp), %rdi             # this = 已分配对象指针（栈顶取出）
    callq Diamond_Diamond                 # 调用构造函数 Diamond_Diamond
    popq %rax                     # 弹出对象指针作为 new 表达式返回值
    # end new Diamond()
    movq %rax, -16(%rbp)       # 存储到局部变量 obj
    # return expr
    movq $0, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    

    .data
    .globl _ZTV1Q             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV1Q:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI1Q       # RTTI type_info 指针（vtable[-1]）
    .quad X_f   # vtable[0]: 虚函数 X_f

    .globl _ZTI1Q             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI1Q:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_Q                 # 指向类型名称字符串
    .quad 1                 # 基类计数（MI 计数风格）
    .quad _ZTI1X                 # base[X] typeinfo 指针
    .quad 0                 # base[X] 子对象偏移（字节）

    .globl _ZTV1P             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV1P:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI1P       # RTTI type_info 指针（vtable[-1]）
    .quad X_f   # vtable[0]: 虚函数 X_f

    .globl _ZTI1P             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI1P:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_P                 # 指向类型名称字符串
    .quad 1                 # 基类计数（MI 计数风格）
    .quad _ZTI1X                 # base[X] typeinfo 指针
    .quad 0                 # base[X] 子对象偏移（字节）

    .globl _ZTV1X             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV1X:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI1X       # RTTI type_info 指针（vtable[-1]）
    .quad X_f   # vtable[0]: 虚函数 X_f

    .globl _ZTI1X             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI1X:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_X                 # 指向类型名称字符串
    .quad 0                 # 无基类（基类计数 = 0）

    .globl _ZTV7Diamond             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV7Diamond:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI7Diamond       # RTTI type_info 指针（vtable[-1]）
    .quad X_f   # vtable[0]: 虚函数 X_f
    # ── secondary vtable for 'Q' @ offset 16 ──
    .quad -16                   # offset-to-top = -16（次基类 'Q' 子对象偏移取反）
    .quad _ZTI7Diamond       # RTTI type_info 指针（次表段的 typeinfo 与主表相同）
    .quad Q_f   # secondary[0]: Q_f（直接引用基类函数）

    .globl _ZTI7Diamond             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI7Diamond:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_Diamond                 # 指向类型名称字符串
    .quad 2                 # 基类计数（MI 计数风格）
    .quad _ZTI1P                 # base[P] typeinfo 指针
    .quad 0                 # base[P] 子对象偏移（字节）
    .quad _ZTI1Q                 # base[Q] typeinfo 指针
    .quad 16                 # base[Q] 子对象偏移（字节）


    .section .rodata
.Ltype_name_Q:                     # 类型名称标签
    .string "Q"           # 类型名称字符串
.Ltype_name_P:                     # 类型名称标签
    .string "P"           # 类型名称字符串
.Ltype_name_X:                     # 类型名称标签
    .string "X"           # 类型名称字符串
.Ltype_name_Diamond:                     # 类型名称标签
    .string "Diamond"           # 类型名称字符串
