# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl A_setA_1             # 导出函数符号，使链接器可见
    A_setA_1:                       # 函数入口标签
    # Function: setA (params: 1)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq %rsi, -16(%rbp)         # 形参 v 从寄存器 spill 到栈
    movq -16(%rbp), %rax    # 加载局部变量 v 到 rax
    pushq %rax                  # 暂存右值到栈上
    movq -8(%rbp), %rax    # 加载 this 指针
    movq %rax, %rcx                # this 地址存入 rcx
    popq %rax                    # 弹出右值回 rax
    movl %eax, 0(%rcx)    # .x = ...（偏移 0，4 字节写入）
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl A_getA             # 导出函数符号，使链接器可见
    A_getA:                       # 函数入口标签
    # Function: getA (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq -8(%rbp), %rax    # 加载 this 指针
    movl 0(%rax), %eax    # 读取字段 .x（偏移 +0 字节）
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl A_A             # 导出函数符号，使链接器可见
    A_A:                       # 函数入口标签
    # Function: A (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl A_dtor             # 导出函数符号，使链接器可见
    A_dtor:                       # 函数入口标签
    # Function: ~A (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl D_D             # 导出函数符号，使链接器可见
    D_D:                       # 函数入口标签
    # Function: D (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl D_dtor             # 导出函数符号，使链接器可见
    D_dtor:                       # 函数入口标签
    # Function: ~D (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl main             # 导出函数符号，使链接器可见
    main:                       # 函数入口标签
    # Function: main (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    # stack object d : D (16 bytes, RAII)
    movq $0, -24(%rbp)    # 零初始化 d 偏移 +0
    movq $0, -16(%rbp)    # 零初始化 d 偏移 +8
    leaq -24(%rbp), %rdi       # this = 栈对象地址 &d
    callq D_D               # 调用构造函数
    # function call
    leaq -24(%rbp), %rax    # 取栈对象地址 &d
    pushq %rax                   # 暂存 this 指针到栈上
    movq $7, %rax           # 整数字面量载入 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rsi                   # 逆序弹出实参到寄存器
    popq %rdi                   # 弹出 this 指针到 rdi（第 0 参数）
    callq A_setA_1                  # 调用方法 A_setA_1
    movq $5, %rax           # 整数字面量载入 rax
    # member assign: .x = ...
    leaq -24(%rbp), %rax    # 取栈对象地址 &d
    movq %rax, %rcx                # 对象地址存入 rcx
    movq $5, %rax           # 整数字面量载入 rax
    movl %eax, 8(%rcx)    # 写入字段 .x（偏移 +8）
    # return expr
    # binary expr
    # binary expr
    # function call
    leaq -24(%rbp), %rax    # 取栈对象地址 &d
    pushq %rax                   # 暂存 this 指针到栈上
    popq %rdi                   # 弹出 this 指针到 rdi（第 0 参数）
    callq A_getA                  # 调用方法 A_getA
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $10, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    imulq %rcx, %rax            # 乘法：rax = rax * rcx（有符号）
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    # member access: .x
    leaq -24(%rbp), %rax    # 取栈对象地址 &d
    movl 8(%rax), %eax    # 读取字段 .x（偏移 +8，4B int）
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~D() before return (RAII, scope exit)
    leaq -24(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq D_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    # ~D() auto at function end (RAII)
    leaq -24(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq D_dtor            # 静态调用析构函数（非虚析构路径）
    
