# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
    # thunk D_getB_thunk16 → D_getB (adjust=-16)
    .globl D_getB_thunk16
    D_getB_thunk16:
    movq  (%rdi), %rax         # vptr
    movq  -16(%rax), %rcx      # vptr[-2] = offset-to-top
    addq  %rcx, %rdi           # this 归顶
    jmp   D_getB              # 跳真实函数
    
    # thunk D_whoAmI_thunk16 → D_whoAmI (adjust=-16)
    .globl D_whoAmI_thunk16
    D_whoAmI_thunk16:
    movq  (%rdi), %rax         # vptr
    movq  -16(%rax), %rcx      # vptr[-2] = offset-to-top
    addq  %rcx, %rdi           # this 归顶
    jmp   D_whoAmI              # 跳真实函数
    
        .globl A_getA
    A_getA:
    # Function: getA (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq -8(%rbp), %rax    # load this
    movl 8(%rax), %eax    # load .a (offset 8)
    leave
    ret
    
        .globl A_whoAmI
    A_whoAmI:
    # Function: whoAmI (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $1, %rax           # int literal
    leave
    ret
    
        .globl A_A
    A_A:
    # Function: A (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV1A(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install primary _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl A_dtor
    A_dtor:
    # Function: ~A (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl B_getB
    B_getB:
    # Function: getB (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq -8(%rbp), %rax    # load this
    movl 8(%rax), %eax    # load .b (offset 8)
    leave
    ret
    
        .globl B_whoAmI
    B_whoAmI:
    # Function: whoAmI (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $2, %rax           # int literal
    leave
    ret
    
        .globl B_B
    B_B:
    # Function: B (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV1B(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install primary _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl B_dtor
    B_dtor:
    # Function: ~B (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl D_D
    D_D:
    # Function: D (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV1D(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install primary _vptr
    leaq _ZTV1D(%rip), %rcx    # secondary vtable for 'B'
    addq $48, %rcx    # skip to secondary[0]
    movq %rcx, 16(%rax)    # install secondary _vptr for 'B'
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl D_getA
    D_getA:
    # Function: getA (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq -8(%rbp), %rax    # load this
    movl 32(%rax), %eax    # load .d (offset 32)
    leave
    ret
    
        .globl D_getB
    D_getB:
    # Function: getB (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq -8(%rbp), %rax    # load this
    movl 32(%rax), %eax    # load .d (offset 32)
    leave
    ret
    
        .globl D_whoAmI
    D_whoAmI:
    # Function: whoAmI (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $3, %rax           # int literal
    leave
    ret
    
        .globl D_dtor
    D_dtor:
    # Function: ~D (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    # var obj = ...
    # new D()
    movq $40, %rdi             # malloc size
    callq malloc                  # allocate memory
    pushq %rax                    # save allocated objPtr
    leaq _ZTV1D(%rip), %rcx    # vtable address
    addq $16, %rcx              # skip to vtable[0]
    movq (%rsp), %rax           # load objPtr
    movq %rcx, (%rax)           # obj._vptr = vtable (primary)
    movq (%rsp), %rax           # load objPtr
    leaq _ZTV1D(%rip), %rcx    # secondary vtable for 'B'
    addq $48, %rcx    # skip to secondary[0]
    movq %rcx, 16(%rax)    # install secondary _vptr for 'B'
    movq (%rsp), %rdi             # this pointer
    callq D_D              # call constructor
    popq %rax                     # return objPtr
    # end new D()
    movq %rax, -16(%rbp)    # store to obj
    movq $100, %rax           # int literal
    # member assign: .a = ...
    movq -16(%rbp), %rax    # load obj
    movq %rax, %rcx                # object address
    movq $100, %rax           # int literal
    movl %eax, 8(%rcx)    # .a (offset 8)
    movq $200, %rax           # int literal
    # member assign: .b = ...
    movq -16(%rbp), %rax    # load obj
    movq %rax, %rcx                # object address
    movq $200, %rax           # int literal
    movl %eax, 24(%rcx)    # .b (offset 24)
    movq $300, %rax           # int literal
    # member assign: .d = ...
    movq -16(%rbp), %rax    # load obj
    movq %rax, %rcx                # object address
    movq $300, %rax           # int literal
    movl %eax, 32(%rcx)    # .d (offset 32)
    # var pa = ...
    movq -16(%rbp), %rax    # load obj
    movq %rax, -24(%rbp)    # store to pa
    # var via_a = ...
    # function call
    movq -24(%rbp), %rax    # load pa
    movq %rax, %rdi            # this = object address
    # VIRTUAL CALL: A::getA (vtable[0])
    pushq %rdi                   # save this (object address)
    popq %rdi                    # this pointer (restored)
    # ═══ Virtual Call Step (a): Read _vptr from object ═══
    movq (%rdi), %rax            # rax = obj._vptr (at offset 0)
    # ═══ Virtual Call Step (b): Load function address from vtable ═══
    movq 0(%rax), %rax       # rax = vtable[0] (offset 0)
    # ═══ Virtual Call Step (c): Jump to the real function ═══
    callq *%rax                  # indirect call via vtable
    # END VIRTUAL CALL A::getA
    movq %rax, -32(%rbp)    # store to via_a
    # var pb = ...
    movq -16(%rbp), %rax    # load obj
    # upcast adjust: D -> B (+16 bytes)
    addq $16, %rax    # upcast adjustment
    movq %rax, -40(%rbp)    # store to pb
    # var via_b = ...
    # function call
    movq -40(%rbp), %rax    # load pb
    movq %rax, %rdi            # this = object address
    # VIRTUAL CALL: B::getB (vtable[0])
    pushq %rdi                   # save this (object address)
    popq %rdi                    # this pointer (restored)
    # ═══ Virtual Call Step (a): Read _vptr from object ═══
    movq (%rdi), %rax            # rax = obj._vptr (at offset 0)
    # ═══ Virtual Call Step (b): Load function address from vtable ═══
    movq 0(%rax), %rax       # rax = vtable[0] (offset 0)
    # ═══ Virtual Call Step (c): Jump to the real function ═══
    callq *%rax                  # indirect call via vtable
    # END VIRTUAL CALL B::getB
    movq %rax, -48(%rbp)    # store to via_b
    # var who_a = ...
    # function call
    movq -24(%rbp), %rax    # load pa
    movq %rax, %rdi            # this = object address
    # VIRTUAL CALL: A::whoAmI (vtable[1])
    pushq %rdi                   # save this (object address)
    popq %rdi                    # this pointer (restored)
    # ═══ Virtual Call Step (a): Read _vptr from object ═══
    movq (%rdi), %rax            # rax = obj._vptr (at offset 0)
    # ═══ Virtual Call Step (b): Load function address from vtable ═══
    movq 8(%rax), %rax       # rax = vtable[1] (offset 8)
    # ═══ Virtual Call Step (c): Jump to the real function ═══
    callq *%rax                  # indirect call via vtable
    # END VIRTUAL CALL A::whoAmI
    movq %rax, -56(%rbp)    # store to who_a
    # var who_b = ...
    # function call
    movq -40(%rbp), %rax    # load pb
    movq %rax, %rdi            # this = object address
    # VIRTUAL CALL: B::whoAmI (vtable[1])
    pushq %rdi                   # save this (object address)
    popq %rdi                    # this pointer (restored)
    # ═══ Virtual Call Step (a): Read _vptr from object ═══
    movq (%rdi), %rax            # rax = obj._vptr (at offset 0)
    # ═══ Virtual Call Step (b): Load function address from vtable ═══
    movq 8(%rax), %rax       # rax = vtable[1] (offset 8)
    # ═══ Virtual Call Step (c): Jump to the real function ═══
    callq *%rax                  # indirect call via vtable
    # END VIRTUAL CALL B::whoAmI
    movq %rax, -64(%rbp)    # store to who_b
    # return expr
    # binary expr
    # binary expr
    # binary expr
    movq -32(%rbp), %rax    # load via_a
    pushq %rax
    movq -48(%rbp), %rax    # load via_b
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    pushq %rax
    movq -56(%rbp), %rax    # load who_a
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    pushq %rax
    movq -64(%rbp), %rax    # load who_b
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    leave
    ret
    

    .data
    .globl _ZTV1D
    .align 8
_ZTV1D:
    .quad 0                    # offset to top (primary)
    .quad _ZTI1D       # RTTI type_info pointer (vtable[-1])
    .quad D_getA   # vtable[0]: D_getA
    .quad D_whoAmI   # vtable[1]: D_whoAmI
    # ── secondary vtable for 'B' @ offset 16 ──
    .quad -16                   # offset to top (secondary 'B')
    .quad _ZTI1D       # RTTI type_info pointer
    .quad D_getB_thunk16   # secondary[0]: D_getB (via thunk, adjust=-16)
    .quad D_whoAmI_thunk16   # secondary[1]: D_whoAmI (via thunk, adjust=-16)

    .globl _ZTI1D
    .align 8
_ZTI1D:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_D                 # type name string
    .quad 2                 # base class count (MI counting-style)
    .quad _ZTI1A                 # base[A] typeinfo
    .quad 0                 # base[A] subobject offset
    .quad _ZTI1B                 # base[B] typeinfo
    .quad 16                 # base[B] subobject offset

    .globl _ZTV1B
    .align 8
_ZTV1B:
    .quad 0                    # offset to top (primary)
    .quad _ZTI1B       # RTTI type_info pointer (vtable[-1])
    .quad B_getB   # vtable[0]: B_getB
    .quad B_whoAmI   # vtable[1]: B_whoAmI

    .globl _ZTI1B
    .align 8
_ZTI1B:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_B                 # type name string
    .quad 0                 # no base classes

    .globl _ZTV1A
    .align 8
_ZTV1A:
    .quad 0                    # offset to top (primary)
    .quad _ZTI1A       # RTTI type_info pointer (vtable[-1])
    .quad A_getA   # vtable[0]: A_getA
    .quad A_whoAmI   # vtable[1]: A_whoAmI

    .globl _ZTI1A
    .align 8
_ZTI1A:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_A                 # type name string
    .quad 0                 # no base classes


    .section .rodata
.Ltype_name_D:
    .string "D"           # type name
.Ltype_name_B:
    .string "B"           # type name
.Ltype_name_A:
    .string "A"           # type name
