# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl X_f             # 导出函数符号，使链接器可见
    X_f:                       # 函数入口标签
    # Function: f (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq $7, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl X_g_1             # 导出函数符号，使链接器可见
    X_g_1:                       # 函数入口标签
    # Function: g (params: 1)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq %rsi, -16(%rbp)         # 形参 k 从寄存器 spill 到栈
    # return expr
    movq -16(%rbp), %rax    # 加载局部变量 k 到 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl X_X             # 导出函数符号，使链接器可见
    X_X:                       # 函数入口标签
    # Function: X (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV1X(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl X_dtor             # 导出函数符号，使链接器可见
    X_dtor:                       # 函数入口标签
    # Function: ~X (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl P_P             # 导出函数符号，使链接器可见
    P_P:                       # 函数入口标签
    # Function: P (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV1P(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl P_dtor             # 导出函数符号，使链接器可见
    P_dtor:                       # 函数入口标签
    # Function: ~P (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Q_Q             # 导出函数符号，使链接器可见
    Q_Q:                       # 函数入口标签
    # Function: Q (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV1Q(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Q_dtor             # 导出函数符号，使链接器可见
    Q_dtor:                       # 函数入口标签
    # Function: ~Q (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Diamond_Diamond             # 导出函数符号，使链接器可见
    Diamond_Diamond:                       # 函数入口标签
    # Function: Diamond (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV7Diamond(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    leaq _ZTV7Diamond(%rip), %rcx    # 取次表首地址（基类 'Q'）
    addq $48, %rcx          # 跳过次表头，指向 secondary[0]
    movq %rcx, 16(%rax)     # 安装次 _vptr（偏移 Q 处）
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Diamond_dtor             # 导出函数符号，使链接器可见
    Diamond_dtor:                       # 函数入口标签
    # Function: ~Diamond (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl C_h             # 导出函数符号，使链接器可见
    C_h:                       # 函数入口标签
    # Function: h (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq $1, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl C_C             # 导出函数符号，使链接器可见
    C_C:                       # 函数入口标签
    # Function: C (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV1C(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl C_dtor             # 导出函数符号，使链接器可见
    C_dtor:                       # 函数入口标签
    # Function: ~C (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl B_h             # 导出函数符号，使链接器可见
    B_h:                       # 函数入口标签
    # Function: h (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq $2, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl B_B             # 导出函数符号，使链接器可见
    B_B:                       # 函数入口标签
    # Function: B (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV1B(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl B_dtor             # 导出函数符号，使链接器可见
    B_dtor:                       # 函数入口标签
    # Function: ~B (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Z_k             # 导出函数符号，使链接器可见
    Z_k:                       # 函数入口标签
    # Function: k (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq $9, %rax           # 整数字面量载入 rax
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Z_Z             # 导出函数符号，使链接器可见
    Z_Z:                       # 函数入口标签
    # Function: Z (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV1Z(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Z_dtor             # 导出函数符号，使链接器可见
    Z_dtor:                       # 函数入口标签
    # Function: ~Z (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl D_D             # 导出函数符号，使链接器可见
    D_D:                       # 函数入口标签
    # Function: D (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV1D(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    leaq _ZTV1D(%rip), %rcx    # 取次表首地址（基类 'B'）
    addq $40, %rcx          # 跳过次表头，指向 secondary[0]
    movq %rcx, 16(%rax)     # 安装次 _vptr（偏移 B 处）
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl D_dtor             # 导出函数符号，使链接器可见
    D_dtor:                       # 函数入口标签
    # Function: ~D (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl main             # 导出函数符号，使链接器可见
    main:                       # 函数入口标签
    # Function: main (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $128, %rsp              # 预留局部变量栈空间（16B 对齐）
    # stack object d : Diamond (32 bytes, RAII)
    movq $0, -40(%rbp)    # 零初始化 d 偏移 +0
    movq $0, -32(%rbp)    # 零初始化 d 偏移 +8
    movq $0, -24(%rbp)    # 零初始化 d 偏移 +16
    movq $0, -16(%rbp)    # 零初始化 d 偏移 +24
    leaq _ZTV7Diamond(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, -40(%rbp)    # 安装主 _vptr 到栈对象
    leaq _ZTV7Diamond(%rip), %rcx    # 取次表首地址（基类 'Q'）
    addq $48, %rcx          # 跳过次表头，指向 secondary[0]
    movq %rcx, -24(%rbp)    # 安装次 _vptr（偏移 Q 处）
    leaq -40(%rbp), %rdi       # this = 栈对象地址 &d
    callq Diamond_Diamond               # 调用构造函数
    # var pq = ...
    leaq -40(%rbp), %rax    # &d = 栈对象地址
    # upcast adjust: Diamond -> Q (+16 bytes)
    addq $16, %rax          # 指针 upcast 偏移调整（+16 字节）
    movq %rax, -48(%rbp)       # 存储到局部变量 pq
    # if condition
    # binary expr
    # function call
    movq -48(%rbp), %rax    # 加载局部变量 pq 到 rax
    movq %rax, %rdi            # this = 对象地址（第 0 参数）
    # VIRTUAL CALL: Q::f (vtable[0])
    pushq %rdi                   # 暂存 this（对象地址）到栈上保护
    popq %rdi                   # 弹出 this 指针（恢复对象地址）
    # ═══ 虚函数调用 (a)：从对象读出 _vptr ═══
    movq (%rdi), %rax            # 从对象首 8 字节读出 _vptr
    # ═══ 虚函数调用 (b)：从 vtable 加载函数地址 ═══
    movq 0(%rax), %rax       # 从 vtable[0] 读出函数地址（偏移 0）
    # ═══ 虚函数调用 (c)：间接跳转到真实函数 ═══
    callq *%rax                  # 经 vtable 间接调用（跳转到 rax 所指地址）
    # END VIRTUAL CALL Q::f
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $7, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_1                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $1, %rax           # 整数字面量载入 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~Diamond() before return (RAII, scope exit)
    leaq -40(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Diamond_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_1:                        # endif 标签
    # if condition
    # binary expr
    # function call
    movq -48(%rbp), %rax    # 加载局部变量 pq 到 rax
    movq %rax, %rdi            # this = 对象地址（第 0 参数）
    # VIRTUAL CALL: Q::g (vtable[1])
    pushq %rdi                   # 暂存 this（对象地址）到栈上保护
    movq $5, %rax           # 整数字面量载入 rax
    pushq %rax                  # 实参值压栈暂存
    popq %rsi                   # 逆序弹出实参到寄存器
    popq %rdi                   # 弹出 this 指针（恢复对象地址）
    # ═══ 虚函数调用 (a)：从对象读出 _vptr ═══
    movq (%rdi), %rax            # 从对象首 8 字节读出 _vptr
    # ═══ 虚函数调用 (b)：从 vtable 加载函数地址 ═══
    movq 8(%rax), %rax       # 从 vtable[1] 读出函数地址（偏移 8）
    # ═══ 虚函数调用 (c)：间接跳转到真实函数 ═══
    callq *%rax                  # 经 vtable 间接调用（跳转到 rax 所指地址）
    # END VIRTUAL CALL Q::g
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $5, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_3                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $2, %rax           # 整数字面量载入 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~Diamond() before return (RAII, scope exit)
    leaq -40(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Diamond_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_3:                        # endif 标签
    # var pp = ...
    leaq -40(%rbp), %rax    # &d = 栈对象地址
    movq %rax, -56(%rbp)       # 存储到局部变量 pp
    # if condition
    # binary expr
    # function call
    movq -56(%rbp), %rax    # 加载局部变量 pp 到 rax
    movq %rax, %rdi            # this = 对象地址（第 0 参数）
    # VIRTUAL CALL: P::f (vtable[0])
    pushq %rdi                   # 暂存 this（对象地址）到栈上保护
    popq %rdi                   # 弹出 this 指针（恢复对象地址）
    # ═══ 虚函数调用 (a)：从对象读出 _vptr ═══
    movq (%rdi), %rax            # 从对象首 8 字节读出 _vptr
    # ═══ 虚函数调用 (b)：从 vtable 加载函数地址 ═══
    movq 0(%rax), %rax       # 从 vtable[0] 读出函数地址（偏移 0）
    # ═══ 虚函数调用 (c)：间接跳转到真实函数 ═══
    callq *%rax                  # 经 vtable 间接调用（跳转到 rax 所指地址）
    # END VIRTUAL CALL P::f
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $7, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_5                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $3, %rax           # 整数字面量载入 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~Diamond() before return (RAII, scope exit)
    leaq -40(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Diamond_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_5:                        # endif 标签
    # stack object dd : D (40 bytes, RAII)
    movq $0, -96(%rbp)    # 零初始化 dd 偏移 +0
    movq $0, -88(%rbp)    # 零初始化 dd 偏移 +8
    movq $0, -80(%rbp)    # 零初始化 dd 偏移 +16
    movq $0, -72(%rbp)    # 零初始化 dd 偏移 +24
    movq $0, -64(%rbp)    # 零初始化 dd 偏移 +32
    leaq _ZTV1D(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, -96(%rbp)    # 安装主 _vptr 到栈对象
    leaq _ZTV1D(%rip), %rcx    # 取次表首地址（基类 'B'）
    addq $40, %rcx          # 跳过次表头，指向 secondary[0]
    movq %rcx, -80(%rbp)    # 安装次 _vptr（偏移 B 处）
    leaq -96(%rbp), %rdi       # this = 栈对象地址 &dd
    callq D_D               # 调用构造函数
    # var pb = ...
    leaq -96(%rbp), %rax    # &dd = 栈对象地址
    # upcast adjust: D -> B (+16 bytes)
    addq $16, %rax          # 指针 upcast 偏移调整（+16 字节）
    movq %rax, -104(%rbp)       # 存储到局部变量 pb
    # if condition
    # binary expr
    # function call
    movq -104(%rbp), %rax    # 加载局部变量 pb 到 rax
    movq %rax, %rdi            # this = 对象地址（第 0 参数）
    # VIRTUAL CALL: B::h (vtable[0])
    pushq %rdi                   # 暂存 this（对象地址）到栈上保护
    popq %rdi                   # 弹出 this 指针（恢复对象地址）
    # ═══ 虚函数调用 (a)：从对象读出 _vptr ═══
    movq (%rdi), %rax            # 从对象首 8 字节读出 _vptr
    # ═══ 虚函数调用 (b)：从 vtable 加载函数地址 ═══
    movq 0(%rax), %rax       # 从 vtable[0] 读出函数地址（偏移 0）
    # ═══ 虚函数调用 (c)：间接跳转到真实函数 ═══
    callq *%rax                  # 经 vtable 间接调用（跳转到 rax 所指地址）
    # END VIRTUAL CALL B::h
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $2, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_7                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $4, %rax           # 整数字面量载入 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~D() before return (RAII, scope exit)
    leaq -96(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq D_dtor            # 静态调用析构函数（非虚析构路径）
    # ~Diamond() before return (RAII, scope exit)
    leaq -40(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Diamond_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_7:                        # endif 标签
    # var pc = ...
    leaq -96(%rbp), %rax    # &dd = 栈对象地址
    # upcast adjust: D -> C (+16 bytes)
    addq $16, %rax          # 指针 upcast 偏移调整（+16 字节）
    movq %rax, -112(%rbp)       # 存储到局部变量 pc
    # if condition
    # binary expr
    # function call
    movq -112(%rbp), %rax    # 加载局部变量 pc 到 rax
    movq %rax, %rdi            # this = 对象地址（第 0 参数）
    # VIRTUAL CALL: C::h (vtable[0])
    pushq %rdi                   # 暂存 this（对象地址）到栈上保护
    popq %rdi                   # 弹出 this 指针（恢复对象地址）
    # ═══ 虚函数调用 (a)：从对象读出 _vptr ═══
    movq (%rdi), %rax            # 从对象首 8 字节读出 _vptr
    # ═══ 虚函数调用 (b)：从 vtable 加载函数地址 ═══
    movq 0(%rax), %rax       # 从 vtable[0] 读出函数地址（偏移 0）
    # ═══ 虚函数调用 (c)：间接跳转到真实函数 ═══
    callq *%rax                  # 经 vtable 间接调用（跳转到 rax 所指地址）
    # END VIRTUAL CALL C::h
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $2, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_9                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $5, %rax           # 整数字面量载入 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~D() before return (RAII, scope exit)
    leaq -96(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq D_dtor            # 静态调用析构函数（非虚析构路径）
    # ~Diamond() before return (RAII, scope exit)
    leaq -40(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Diamond_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_9:                        # endif 标签
    # var pz = ...
    leaq -96(%rbp), %rax    # &dd = 栈对象地址
    movq %rax, -120(%rbp)       # 存储到局部变量 pz
    # if condition
    # binary expr
    # function call
    movq -120(%rbp), %rax    # 加载局部变量 pz 到 rax
    movq %rax, %rdi            # this = 对象地址（第 0 参数）
    # VIRTUAL CALL: Z::k (vtable[0])
    pushq %rdi                   # 暂存 this（对象地址）到栈上保护
    popq %rdi                   # 弹出 this 指针（恢复对象地址）
    # ═══ 虚函数调用 (a)：从对象读出 _vptr ═══
    movq (%rdi), %rax            # 从对象首 8 字节读出 _vptr
    # ═══ 虚函数调用 (b)：从 vtable 加载函数地址 ═══
    movq 0(%rax), %rax       # 从 vtable[0] 读出函数地址（偏移 0）
    # ═══ 虚函数调用 (c)：间接跳转到真实函数 ═══
    callq *%rax                  # 经 vtable 间接调用（跳转到 rax 所指地址）
    # END VIRTUAL CALL Z::k
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $9, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    cmpq %rcx, %rax             # 比较：rax - rcx 设置标志位
    setne %al                   # 不等时 al = 1（ZF=0）
    movzbq %al, %rax            # 零扩展 al 到 64 位 rax
    testq %rax, %rax             # 条件值与自身按位与，设置 ZF 标志位
    je endif_11                     # 条件为假（ZF=1）跳转到 else/endif
    # then branch
    # return expr
    movq $6, %rax           # 整数字面量载入 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~D() before return (RAII, scope exit)
    leaq -96(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq D_dtor            # 静态调用析构函数（非虚析构路径）
    # ~Diamond() before return (RAII, scope exit)
    leaq -40(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Diamond_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    endif_11:                        # endif 标签
    # return expr
    movq $0, %rax           # 整数字面量载入 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~D() before return (RAII, scope exit)
    leaq -96(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq D_dtor            # 静态调用析构函数（非虚析构路径）
    # ~Diamond() before return (RAII, scope exit)
    leaq -40(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Diamond_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    # ~D() auto at function end (RAII)
    leaq -96(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq D_dtor            # 静态调用析构函数（非虚析构路径）
    # ~Diamond() auto at function end (RAII)
    leaq -40(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Diamond_dtor            # 静态调用析构函数（非虚析构路径）
    

    .data
    .globl _ZTV1B             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV1B:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI1B       # RTTI type_info 指针（vtable[-1]）
    .quad B_h   # vtable[0]: 虚函数 B_h

    .globl _ZTI1B             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI1B:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_B                 # 指向类型名称字符串
    .quad 1                 # 基类计数（MI 计数风格）
    .quad _ZTI1C                 # base[C] typeinfo 指针
    .quad 0                 # base[C] 子对象偏移（字节）

    .globl _ZTV1D             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV1D:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI1D       # RTTI type_info 指针（vtable[-1]）
    .quad Z_k   # vtable[0]: 虚函数 Z_k
    # ── secondary vtable for 'B' @ offset 16 ──
    .quad -16                   # offset-to-top = -16（次基类 'B' 子对象偏移取反）
    .quad _ZTI1D       # RTTI type_info 指针（次表段的 typeinfo 与主表相同）
    .quad B_h   # secondary[0]: B_h（直接引用基类函数）

    .globl _ZTI1D             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI1D:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_D                 # 指向类型名称字符串
    .quad 2                 # 基类计数（MI 计数风格）
    .quad _ZTI1Z                 # base[Z] typeinfo 指针
    .quad 0                 # base[Z] 子对象偏移（字节）
    .quad _ZTI1B                 # base[B] typeinfo 指针
    .quad 16                 # base[B] 子对象偏移（字节）

    .globl _ZTV1C             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV1C:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI1C       # RTTI type_info 指针（vtable[-1]）
    .quad C_h   # vtable[0]: 虚函数 C_h

    .globl _ZTI1C             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI1C:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_C                 # 指向类型名称字符串
    .quad 0                 # 无基类（基类计数 = 0）

    .globl _ZTV1Q             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV1Q:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI1Q       # RTTI type_info 指针（vtable[-1]）
    .quad X_f   # vtable[0]: 虚函数 X_f
    .quad X_g_1   # vtable[1]: 虚函数 X_g_1

    .globl _ZTI1Q             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI1Q:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_Q                 # 指向类型名称字符串
    .quad 1                 # 基类计数（MI 计数风格）
    .quad _ZTI1X                 # base[X] typeinfo 指针
    .quad 0                 # base[X] 子对象偏移（字节）

    .globl _ZTV1Z             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV1Z:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI1Z       # RTTI type_info 指针（vtable[-1]）
    .quad Z_k   # vtable[0]: 虚函数 Z_k

    .globl _ZTI1Z             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI1Z:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_Z                 # 指向类型名称字符串
    .quad 0                 # 无基类（基类计数 = 0）

    .globl _ZTV1P             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV1P:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI1P       # RTTI type_info 指针（vtable[-1]）
    .quad X_f   # vtable[0]: 虚函数 X_f
    .quad X_g_1   # vtable[1]: 虚函数 X_g_1

    .globl _ZTI1P             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI1P:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_P                 # 指向类型名称字符串
    .quad 1                 # 基类计数（MI 计数风格）
    .quad _ZTI1X                 # base[X] typeinfo 指针
    .quad 0                 # base[X] 子对象偏移（字节）

    .globl _ZTV1X             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV1X:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI1X       # RTTI type_info 指针（vtable[-1]）
    .quad X_f   # vtable[0]: 虚函数 X_f
    .quad X_g_1   # vtable[1]: 虚函数 X_g_1

    .globl _ZTI1X             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI1X:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_X                 # 指向类型名称字符串
    .quad 0                 # 无基类（基类计数 = 0）

    .globl _ZTV7Diamond             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV7Diamond:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI7Diamond       # RTTI type_info 指针（vtable[-1]）
    .quad X_f   # vtable[0]: 虚函数 X_f
    .quad X_g_1   # vtable[1]: 虚函数 X_g_1
    # ── secondary vtable for 'Q' @ offset 16 ──
    .quad -16                   # offset-to-top = -16（次基类 'Q' 子对象偏移取反）
    .quad _ZTI7Diamond       # RTTI type_info 指针（次表段的 typeinfo 与主表相同）
    .quad X_f   # secondary[0]: X_f（直接引用基类函数）
    .quad X_g_1   # secondary[1]: X_g_1（直接引用基类函数）

    .globl _ZTI7Diamond             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI7Diamond:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_Diamond                 # 指向类型名称字符串
    .quad 2                 # 基类计数（MI 计数风格）
    .quad _ZTI1P                 # base[P] typeinfo 指针
    .quad 0                 # base[P] 子对象偏移（字节）
    .quad _ZTI1Q                 # base[Q] typeinfo 指针
    .quad 16                 # base[Q] 子对象偏移（字节）


    .section .rodata
.Ltype_name_B:                     # 类型名称标签
    .string "B"           # 类型名称字符串
.Ltype_name_D:                     # 类型名称标签
    .string "D"           # 类型名称字符串
.Ltype_name_C:                     # 类型名称标签
    .string "C"           # 类型名称字符串
.Ltype_name_Q:                     # 类型名称标签
    .string "Q"           # 类型名称字符串
.Ltype_name_Z:                     # 类型名称标签
    .string "Z"           # 类型名称字符串
.Ltype_name_P:                     # 类型名称标签
    .string "P"           # 类型名称字符串
.Ltype_name_X:                     # 类型名称标签
    .string "X"           # 类型名称字符串
.Ltype_name_Diamond:                     # 类型名称标签
    .string "Diamond"           # 类型名称字符串
