# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
    # thunk Middle_getB2_thunk16 → Middle_getB2 (adjust=-16)
    .globl Middle_getB2_thunk16             # 导出 thunk 符号供链接器可见
    Middle_getB2_thunk16:                   # thunk 跳板入口标签
    movq  (%rdi), %rax         # 从 this 首 8 字节读出 _vptr
    movq  -16(%rax), %rcx      # vptr[-2] = offset-to-top（次基类→最派生偏移）
    addq  %rcx, %rdi           # this += offset-to-top，归顶到最派生对象
    jmp   Middle_getB2              # 无条件跳转到真实函数（已归顶的 this 直入）
    
        .globl Base1_getB1             # 导出函数符号，使链接器可见
    Base1_getB1:                       # 函数入口标签
    # Function: getB1 (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq -8(%rbp), %rax    # 加载 this 指针
    movl 8(%rax), %eax    # 读取字段 .b1（偏移 +8 字节）
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Base1_Base1             # 导出函数符号，使链接器可见
    Base1_Base1:                       # 函数入口标签
    # Function: Base1 (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV5Base1(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Base1_dtor             # 导出函数符号，使链接器可见
    Base1_dtor:                       # 函数入口标签
    # Function: ~Base1 (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Base2_getB2             # 导出函数符号，使链接器可见
    Base2_getB2:                       # 函数入口标签
    # Function: getB2 (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq -8(%rbp), %rax    # 加载 this 指针
    movl 8(%rax), %eax    # 读取字段 .b2（偏移 +8 字节）
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Base2_Base2             # 导出函数符号，使链接器可见
    Base2_Base2:                       # 函数入口标签
    # Function: Base2 (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV5Base2(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Base2_dtor             # 导出函数符号，使链接器可见
    Base2_dtor:                       # 函数入口标签
    # Function: ~Base2 (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Middle_getMid             # 导出函数符号，使链接器可见
    Middle_getMid:                       # 函数入口标签
    # Function: getMid (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq -8(%rbp), %rax    # 加载 this 指针
    movl 32(%rax), %eax    # 读取字段 .mid（偏移 +32 字节）
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Middle_getB1             # 导出函数符号，使链接器可见
    Middle_getB1:                       # 函数入口标签
    # Function: getB1 (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq -8(%rbp), %rax    # 加载 this 指针
    movl 8(%rax), %eax    # 读取字段 .b1（偏移 +8 字节）
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Middle_getB2             # 导出函数符号，使链接器可见
    Middle_getB2:                       # 函数入口标签
    # Function: getB2 (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq -8(%rbp), %rax    # 加载 this 指针
    movl 24(%rax), %eax    # 读取字段 .b2（偏移 +24 字节）
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Middle_Middle             # 导出函数符号，使链接器可见
    Middle_Middle:                       # 函数入口标签
    # Function: Middle (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV6Middle(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    leaq _ZTV6Middle(%rip), %rcx    # 取次表首地址（基类 'Base2'）
    addq $48, %rcx          # 跳过次表头，指向 secondary[0]
    movq %rcx, 16(%rax)     # 安装次 _vptr（偏移 Base2 处）
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Middle_dtor             # 导出函数符号，使链接器可见
    Middle_dtor:                       # 函数入口标签
    # Function: ~Middle (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Final_getFinal             # 导出函数符号，使链接器可见
    Final_getFinal:                       # 函数入口标签
    # Function: getFinal (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq -8(%rbp), %rax    # 加载 this 指针
    movl 40(%rax), %eax    # 读取字段 .final_val（偏移 +40 字节）
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Final_getB1             # 导出函数符号，使链接器可见
    Final_getB1:                       # 函数入口标签
    # Function: getB1 (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq -8(%rbp), %rax    # 加载 this 指针
    movl 8(%rax), %eax    # 读取字段 .b1（偏移 +8 字节）
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Final_getB2             # 导出函数符号，使链接器可见
    Final_getB2:                       # 函数入口标签
    # Function: getB2 (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq -8(%rbp), %rax    # 加载 this 指针
    movl 24(%rax), %eax    # 读取字段 .b2（偏移 +24 字节）
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Final_getMid             # 导出函数符号，使链接器可见
    Final_getMid:                       # 函数入口标签
    # Function: getMid (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # return expr
    movq -8(%rbp), %rax    # 加载 this 指针
    movl 32(%rax), %eax    # 读取字段 .mid（偏移 +32 字节）
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Final_Final             # 导出函数符号，使链接器可见
    Final_Final:                       # 函数入口标签
    # Function: Final (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq -8(%rbp), %rax         # 加载 this 指针
    leaq _ZTV5Final(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Final_dtor             # 导出函数符号，使链接器可见
    Final_dtor:                       # 函数入口标签
    # Function: ~Final (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq $0, %rax               # void 函数返回 0
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl main             # 导出函数符号，使链接器可见
    main:                       # 函数入口标签
    # Function: main (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    # var obj = ...
    # new Final()
    movq $48, %rdi             # malloc 分配大小：48 字节
    callq malloc                  # 调用 malloc 分配堆内存
    pushq %rax                    # 暂存返回的对象指针到栈上
    leaq _ZTV5Final(%rip), %rcx    # 取 vtable 首地址
    addq $16, %rcx              # 跳过 offset-to-top 与 RTTI，指向 vtable[0]
    movq (%rsp), %rax           # 从栈上取回对象指针
    movq %rcx, (%rax)           # 安装主 _vptr 到对象首 8 字节
    movq (%rsp), %rdi             # this = 已分配对象指针（栈顶取出）
    callq Final_Final                 # 调用构造函数 Final_Final
    popq %rax                     # 弹出对象指针作为 new 表达式返回值
    # end new Final()
    movq %rax, -16(%rbp)       # 存储到局部变量 obj
    movq $1, %rax           # 整数字面量载入 rax
    # member assign: .b1 = ...
    movq -16(%rbp), %rax    # 加载局部变量 obj 到 rax
    movq %rax, %rcx                # 对象地址存入 rcx
    movq $1, %rax           # 整数字面量载入 rax
    movl %eax, 8(%rcx)    # 写入字段 .b1（偏移 +8）
    movq $2, %rax           # 整数字面量载入 rax
    # member assign: .b2 = ...
    movq -16(%rbp), %rax    # 加载局部变量 obj 到 rax
    movq %rax, %rcx                # 对象地址存入 rcx
    movq $2, %rax           # 整数字面量载入 rax
    movl %eax, 24(%rcx)    # 写入字段 .b2（偏移 +24）
    movq $10, %rax           # 整数字面量载入 rax
    # member assign: .mid = ...
    movq -16(%rbp), %rax    # 加载局部变量 obj 到 rax
    movq %rax, %rcx                # 对象地址存入 rcx
    movq $10, %rax           # 整数字面量载入 rax
    movl %eax, 32(%rcx)    # 写入字段 .mid（偏移 +32）
    movq $100, %rax           # 整数字面量载入 rax
    # member assign: .final_val = ...
    movq -16(%rbp), %rax    # 加载局部变量 obj 到 rax
    movq %rax, %rcx                # 对象地址存入 rcx
    movq $100, %rax           # 整数字面量载入 rax
    movl %eax, 40(%rcx)    # 写入字段 .final_val（偏移 +40）
    # return expr
    # binary expr
    # binary expr
    # binary expr
    # function call
    movq -16(%rbp), %rax    # 加载局部变量 obj 到 rax
    movq %rax, %rdi            # this = 对象地址（第 0 参数）
    # VIRTUAL CALL: Final::getB1 (vtable[0])
    pushq %rdi                   # 暂存 this（对象地址）到栈上保护
    popq %rdi                   # 弹出 this 指针（恢复对象地址）
    # ═══ 虚函数调用 (a)：从对象读出 _vptr ═══
    movq (%rdi), %rax            # 从对象首 8 字节读出 _vptr
    # ═══ 虚函数调用 (b)：从 vtable 加载函数地址 ═══
    movq 0(%rax), %rax       # 从 vtable[0] 读出函数地址（偏移 0）
    # ═══ 虚函数调用 (c)：间接跳转到真实函数 ═══
    callq *%rax                  # 经 vtable 间接调用（跳转到 rax 所指地址）
    # END VIRTUAL CALL Final::getB1
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    # function call
    movq -16(%rbp), %rax    # 加载局部变量 obj 到 rax
    movq %rax, %rdi            # this = 对象地址（第 0 参数）
    # VIRTUAL CALL: Final::getB2 (vtable[3])
    pushq %rdi                   # 暂存 this（对象地址）到栈上保护
    popq %rdi                   # 弹出 this 指针（恢复对象地址）
    # ═══ 虚函数调用 (a)：从对象读出 _vptr ═══
    movq (%rdi), %rax            # 从对象首 8 字节读出 _vptr
    # ═══ 虚函数调用 (b)：从 vtable 加载函数地址 ═══
    movq 24(%rax), %rax       # 从 vtable[3] 读出函数地址（偏移 24）
    # ═══ 虚函数调用 (c)：间接跳转到真实函数 ═══
    callq *%rax                  # 经 vtable 间接调用（跳转到 rax 所指地址）
    # END VIRTUAL CALL Final::getB2
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    # function call
    movq -16(%rbp), %rax    # 加载局部变量 obj 到 rax
    movq %rax, %rdi            # this = 对象地址（第 0 参数）
    # VIRTUAL CALL: Final::getMid (vtable[1])
    pushq %rdi                   # 暂存 this（对象地址）到栈上保护
    popq %rdi                   # 弹出 this 指针（恢复对象地址）
    # ═══ 虚函数调用 (a)：从对象读出 _vptr ═══
    movq (%rdi), %rax            # 从对象首 8 字节读出 _vptr
    # ═══ 虚函数调用 (b)：从 vtable 加载函数地址 ═══
    movq 8(%rax), %rax       # 从 vtable[1] 读出函数地址（偏移 8）
    # ═══ 虚函数调用 (c)：间接跳转到真实函数 ═══
    callq *%rax                  # 经 vtable 间接调用（跳转到 rax 所指地址）
    # END VIRTUAL CALL Final::getMid
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    # function call
    movq -16(%rbp), %rax    # 加载局部变量 obj 到 rax
    movq %rax, %rdi            # this = 对象地址（第 0 参数）
    # VIRTUAL CALL: Final::getFinal (vtable[2])
    pushq %rdi                   # 暂存 this（对象地址）到栈上保护
    popq %rdi                   # 弹出 this 指针（恢复对象地址）
    # ═══ 虚函数调用 (a)：从对象读出 _vptr ═══
    movq (%rdi), %rax            # 从对象首 8 字节读出 _vptr
    # ═══ 虚函数调用 (b)：从 vtable 加载函数地址 ═══
    movq 16(%rax), %rax       # 从 vtable[2] 读出函数地址（偏移 16）
    # ═══ 虚函数调用 (c)：间接跳转到真实函数 ═══
    callq *%rax                  # 经 vtable 间接调用（跳转到 rax 所指地址）
    # END VIRTUAL CALL Final::getFinal
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    

    .data
    .globl _ZTV5Final             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV5Final:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI5Final       # RTTI type_info 指针（vtable[-1]）
    .quad Final_getB1   # vtable[0]: 虚函数 Final_getB1
    .quad Final_getMid   # vtable[1]: 虚函数 Final_getMid
    .quad Final_getFinal   # vtable[2]: 虚函数 Final_getFinal
    .quad Final_getB2   # vtable[3]: 虚函数 Final_getB2

    .globl _ZTI5Final             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI5Final:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_Final                 # 指向类型名称字符串
    .quad 1                 # 基类计数（MI 计数风格）
    .quad _ZTI6Middle                 # base[Middle] typeinfo 指针
    .quad 0                 # base[Middle] 子对象偏移（字节）

    .globl _ZTV6Middle             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV6Middle:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI6Middle       # RTTI type_info 指针（vtable[-1]）
    .quad Middle_getB1   # vtable[0]: 虚函数 Middle_getB1
    .quad Middle_getMid   # vtable[1]: 虚函数 Middle_getMid
    # ── secondary vtable for 'Base2' @ offset 16 ──
    .quad -16                   # offset-to-top = -16（次基类 'Base2' 子对象偏移取反）
    .quad _ZTI6Middle       # RTTI type_info 指针（次表段的 typeinfo 与主表相同）
    .quad Middle_getB2_thunk16   # secondary[0]: Middle_getB2（经 thunk 跳板，this 调整量=-16）

    .globl _ZTI6Middle             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI6Middle:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_Middle                 # 指向类型名称字符串
    .quad 2                 # 基类计数（MI 计数风格）
    .quad _ZTI5Base1                 # base[Base1] typeinfo 指针
    .quad 0                 # base[Base1] 子对象偏移（字节）
    .quad _ZTI5Base2                 # base[Base2] typeinfo 指针
    .quad 16                 # base[Base2] 子对象偏移（字节）

    .globl _ZTV5Base2             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV5Base2:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI5Base2       # RTTI type_info 指针（vtable[-1]）
    .quad Base2_getB2   # vtable[0]: 虚函数 Base2_getB2

    .globl _ZTI5Base2             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI5Base2:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_Base2                 # 指向类型名称字符串
    .quad 0                 # 无基类（基类计数 = 0）

    .globl _ZTV5Base1             # 导出 vtable 符号
    .align 8                # 8 字节对齐
_ZTV5Base1:                        # vtable 标签
    .quad 0                    # offset-to-top = 0（主基类子对象与对象起始重合）
    .quad _ZTI5Base1       # RTTI type_info 指针（vtable[-1]）
    .quad Base1_getB1   # vtable[0]: 虚函数 Base1_getB1

    .globl _ZTI5Base1             # 导出 RTTI 符号
    .align 8                # 8 字节对齐
_ZTI5Base1:                        # typeinfo 标签
    .quad 0                    # type_info vtable = 0（简化版，未链接真实 RTTI）
    .quad .Ltype_name_Base1                 # 指向类型名称字符串
    .quad 0                 # 无基类（基类计数 = 0）


    .section .rodata
.Ltype_name_Final:                     # 类型名称标签
    .string "Final"           # 类型名称字符串
.Ltype_name_Middle:                     # 类型名称标签
    .string "Middle"           # 类型名称字符串
.Ltype_name_Base2:                     # 类型名称标签
    .string "Base2"           # 类型名称字符串
.Ltype_name_Base1:                     # 类型名称标签
    .string "Base1"           # 类型名称字符串
