# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
    # thunk Bottom_getBase_thunk24 → Bottom_getBase (adjust=-24)
    .globl Bottom_getBase_thunk24
    Bottom_getBase_thunk24:
    movq  (%rdi), %rax         # vptr
    movq  -16(%rax), %rcx      # vptr[-2] = offset-to-top
    addq  %rcx, %rdi           # this 归顶
    jmp   Bottom_getBase              # 跳真实函数
    
    # thunk Bottom_getRight_thunk24 → Bottom_getRight (adjust=-24)
    .globl Bottom_getRight_thunk24
    Bottom_getRight_thunk24:
    movq  (%rdi), %rax         # vptr
    movq  -16(%rax), %rcx      # vptr[-2] = offset-to-top
    addq  %rcx, %rdi           # this 归顶
    jmp   Bottom_getRight              # 跳真实函数
    
        .globl Base_getBase
    Base_getBase:
    # Function: getBase (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq -8(%rbp), %rax    # load this
    movl 8(%rax), %eax    # load .base_val (offset 8)
    leave
    ret
    
        .globl Base_Base
    Base_Base:
    # Function: Base (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV4Base(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install primary _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Base_dtor
    Base_dtor:
    # Function: ~Base (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl Left_getLeft
    Left_getLeft:
    # Function: getLeft (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq -8(%rbp), %rax    # load this
    movl 16(%rax), %eax    # load .left_val (offset 16)
    leave
    ret
    
        .globl Left_getBase
    Left_getBase:
    # Function: getBase (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq -8(%rbp), %rax    # load this
    movl 8(%rax), %eax    # load .base_val (offset 8)
    leave
    ret
    
        .globl Left_Left
    Left_Left:
    # Function: Left (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV4Left(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install primary _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Left_dtor
    Left_dtor:
    # Function: ~Left (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl Right_getRight
    Right_getRight:
    # Function: getRight (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq -8(%rbp), %rax    # load this
    movl 16(%rax), %eax    # load .right_val (offset 16)
    leave
    ret
    
        .globl Right_getBase
    Right_getBase:
    # Function: getBase (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq -8(%rbp), %rax    # load this
    movl 8(%rax), %eax    # load .base_val (offset 8)
    leave
    ret
    
        .globl Right_Right
    Right_Right:
    # Function: Right (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV5Right(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install primary _vptr
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Right_dtor
    Right_dtor:
    # Function: ~Right (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl Bottom_getBottom
    Bottom_getBottom:
    # Function: getBottom (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq -8(%rbp), %rax    # load this
    movl 48(%rax), %eax    # load .bottom_val (offset 48)
    leave
    ret
    
        .globl Bottom_getBase
    Bottom_getBase:
    # Function: getBase (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $0, %rax           # int literal
    leave
    ret
    
        .globl Bottom_getLeft
    Bottom_getLeft:
    # Function: getLeft (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $0, %rax           # int literal
    leave
    ret
    
        .globl Bottom_getRight
    Bottom_getRight:
    # Function: getRight (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    movq $0, %rax           # int literal
    leave
    ret
    
        .globl Bottom_Bottom
    Bottom_Bottom:
    # Function: Bottom (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq -8(%rbp), %rax    # this
    leaq _ZTV6Bottom(%rip), %rcx    # vtable pointer
    addq $16, %rcx    # skip top+rtti to vtable[0]
    movq %rcx, (%rax)    # install primary _vptr
    leaq _ZTV6Bottom(%rip), %rcx    # secondary vtable for 'Right'
    addq $56, %rcx    # skip to secondary[0]
    movq %rcx, 24(%rax)    # install secondary _vptr for 'Right'
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Bottom_dtor
    Bottom_dtor:
    # Function: ~Bottom (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    # var obj = ...
    # new Bottom()
    movq $56, %rdi             # malloc size
    callq malloc                  # allocate memory
    pushq %rax                    # save allocated objPtr
    leaq _ZTV6Bottom(%rip), %rcx    # vtable address
    addq $16, %rcx              # skip to vtable[0]
    movq (%rsp), %rax           # load objPtr
    movq %rcx, (%rax)           # obj._vptr = vtable (primary)
    movq (%rsp), %rax           # load objPtr
    leaq _ZTV6Bottom(%rip), %rcx    # secondary vtable for 'Right'
    addq $56, %rcx    # skip to secondary[0]
    movq %rcx, 24(%rax)    # install secondary _vptr for 'Right'
    movq (%rsp), %rdi             # this pointer
    callq Bottom_Bottom              # call constructor
    popq %rax                     # return objPtr
    # end new Bottom()
    movq %rax, -16(%rbp)    # store to obj
    movq $30, %rax           # int literal
    # member assign: .bottom_val = ...
    movq -16(%rbp), %rax    # load obj
    movq %rax, %rcx                # object address
    movq $30, %rax           # int literal
    movl %eax, 48(%rcx)    # .bottom_val (offset 48)
    # return expr
    # function call
    movq -16(%rbp), %rax    # load obj
    movq %rax, %rdi            # this = object address
    # VIRTUAL CALL: Bottom::getBottom (vtable[2])
    pushq %rdi                   # save this (object address)
    popq %rdi                    # this pointer (restored)
    # ═══ Virtual Call Step (a): Read _vptr from object ═══
    movq (%rdi), %rax            # rax = obj._vptr (at offset 0)
    # ═══ Virtual Call Step (b): Load function address from vtable ═══
    movq 16(%rax), %rax       # rax = vtable[2] (offset 16)
    # ═══ Virtual Call Step (c): Jump to the real function ═══
    callq *%rax                  # indirect call via vtable
    # END VIRTUAL CALL Bottom::getBottom
    leave
    ret
    

    .data
    .globl _ZTV6Bottom
    .align 8
_ZTV6Bottom:
    .quad 0                    # offset to top (primary)
    .quad _ZTI6Bottom       # RTTI type_info pointer (vtable[-1])
    .quad Bottom_getBase   # vtable[0]: Bottom_getBase
    .quad Bottom_getLeft   # vtable[1]: Bottom_getLeft
    .quad Bottom_getBottom   # vtable[2]: Bottom_getBottom
    # ── secondary vtable for 'Right' @ offset 24 ──
    .quad -24                   # offset to top (secondary 'Right')
    .quad _ZTI6Bottom       # RTTI type_info pointer
    .quad Bottom_getBase_thunk24   # secondary[0]: Bottom_getBase (via thunk, adjust=-24)
    .quad Bottom_getRight_thunk24   # secondary[1]: Bottom_getRight (via thunk, adjust=-24)

    .globl _ZTI6Bottom
    .align 8
_ZTI6Bottom:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Bottom                 # type name string
    .quad 2                 # base class count (MI counting-style)
    .quad _ZTI4Left                 # base[Left] typeinfo
    .quad 0                 # base[Left] subobject offset
    .quad _ZTI5Right                 # base[Right] typeinfo
    .quad 24                 # base[Right] subobject offset

    .globl _ZTV5Right
    .align 8
_ZTV5Right:
    .quad 0                    # offset to top (primary)
    .quad _ZTI5Right       # RTTI type_info pointer (vtable[-1])
    .quad Right_getBase   # vtable[0]: Right_getBase
    .quad Right_getRight   # vtable[1]: Right_getRight

    .globl _ZTI5Right
    .align 8
_ZTI5Right:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Right                 # type name string
    .quad 1                 # base class count (MI counting-style)
    .quad _ZTI4Base                 # base[Base] typeinfo
    .quad 0                 # base[Base] subobject offset

    .globl _ZTV4Left
    .align 8
_ZTV4Left:
    .quad 0                    # offset to top (primary)
    .quad _ZTI4Left       # RTTI type_info pointer (vtable[-1])
    .quad Left_getBase   # vtable[0]: Left_getBase
    .quad Left_getLeft   # vtable[1]: Left_getLeft

    .globl _ZTI4Left
    .align 8
_ZTI4Left:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Left                 # type name string
    .quad 1                 # base class count (MI counting-style)
    .quad _ZTI4Base                 # base[Base] typeinfo
    .quad 0                 # base[Base] subobject offset

    .globl _ZTV4Base
    .align 8
_ZTV4Base:
    .quad 0                    # offset to top (primary)
    .quad _ZTI4Base       # RTTI type_info pointer (vtable[-1])
    .quad Base_getBase   # vtable[0]: Base_getBase

    .globl _ZTI4Base
    .align 8
_ZTI4Base:
    .quad 0                    # type_info vtable (simplified)
    .quad .Ltype_name_Base                 # type name string
    .quad 0                 # no base classes


    .section .rodata
.Ltype_name_Bottom:
    .string "Bottom"           # type name
.Ltype_name_Right:
    .string "Right"           # type name
.Ltype_name_Left:
    .string "Left"           # type name
.Ltype_name_Base:
    .string "Base"           # type name
