# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl Tracer_Tracer_1             # 导出函数符号，使链接器可见
    Tracer_Tracer_1:                       # 函数入口标签
    # Function: Tracer (params: 1)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    movq %rsi, -16(%rbp)         # 形参 i 从寄存器 spill 到栈
    movq -16(%rbp), %rax    # 加载局部变量 i 到 rax
    movq -8(%rbp), %rcx       # 加载 this 指针
    movl %eax, 0(%rcx)    # 初始化字段 id（偏移 0，4B）
    movq -8(%rbp), %rax         # 构造函数返回 this 指针
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl Tracer_dtor             # 导出函数符号，使链接器可见
    Tracer_dtor:                       # 函数入口标签
    # Function: ~Tracer (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    movq %rdi, -8(%rbp)         # 保存 this 指针到栈槽
    # binary expr
    # binary expr
    movq g(%rip), %rax    # 加载全局变量 g 到 rax（RIP 相对寻址）
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq $10, %rax           # 整数字面量载入 rax
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    imulq %rcx, %rax            # 乘法：rax = rax * rcx（有符号）
    pushq %rax                  # 左操作数压栈暂存（求右值会覆盖 rax）
    movq -8(%rbp), %rax    # 加载 this 指针
    movl 0(%rax), %eax    # 读取字段 .id（偏移 +0 字节）
    movq %rax, %rcx             # 右操作数从 rax 转移到 rcx
    popq %rax                   # 弹出左操作数回到 rax
    addq %rcx, %rax             # 加法：rax = rax + rcx
    movq %rax, g(%rip)       # 全局变量 g = ...
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    
        .globl f             # 导出函数符号，使链接器可见
    f:                       # 函数入口标签
    # Function: f (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    # stack object a : Tracer (8 bytes, RAII)
    movq $0, -16(%rbp)    # 零初始化 a 偏移 +0
    movq $1, %rax           # 整数字面量载入 rax
    pushq %rax                  # 构造实参压栈暂存
    popq %rsi                   # 逆序弹出实参到寄存器
    leaq -16(%rbp), %rdi       # this = 栈对象地址 &a
    callq Tracer_Tracer_1               # 调用构造函数（带参重载）
    # return expr
    movq $0, %rax           # 整数字面量载入 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~Tracer() before return (RAII, scope exit)
    leaq -16(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Tracer_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    # ~Tracer() auto at function end (RAII)
    leaq -16(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Tracer_dtor            # 静态调用析构函数（非虚析构路径）
    
        .globl h             # 导出函数符号，使链接器可见
    h:                       # 函数入口标签
    # Function: h (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    # stack object a : Tracer (8 bytes, RAII)
    movq $0, -16(%rbp)    # 零初始化 a 偏移 +0
    movq $1, %rax           # 整数字面量载入 rax
    pushq %rax                  # 构造实参压栈暂存
    popq %rsi                   # 逆序弹出实参到寄存器
    leaq -16(%rbp), %rdi       # this = 栈对象地址 &a
    callq Tracer_Tracer_1               # 调用构造函数（带参重载）
    # stack object b : Tracer (8 bytes, RAII)
    movq $0, -24(%rbp)    # 零初始化 b 偏移 +0
    movq $2, %rax           # 整数字面量载入 rax
    pushq %rax                  # 构造实参压栈暂存
    popq %rsi                   # 逆序弹出实参到寄存器
    leaq -24(%rbp), %rdi       # this = 栈对象地址 &b
    callq Tracer_Tracer_1               # 调用构造函数（带参重载）
    # return expr
    movq $0, %rax           # 整数字面量载入 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~Tracer() before return (RAII, scope exit)
    leaq -24(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Tracer_dtor            # 静态调用析构函数（非虚析构路径）
    # ~Tracer() before return (RAII, scope exit)
    leaq -16(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Tracer_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    # ~Tracer() auto at block end (RAII, reverse order)
    leaq -24(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Tracer_dtor            # 静态调用析构函数（非虚析构路径）
    # return expr
    movq $0, %rax           # 整数字面量载入 rax
    pushq %rax                  # 保护返回值（析构调用会踩掉 rax）
    # ~Tracer() before return (RAII, scope exit)
    leaq -16(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Tracer_dtor            # 静态调用析构函数（非虚析构路径）
    popq %rax                   # 恢复返回值
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    # ~Tracer() auto at function end (RAII)
    leaq -16(%rbp), %rdi       # this = 栈上对象地址（直接取址，无指针变量）
    callq Tracer_dtor            # 静态调用析构函数（非虚析构路径）
    
        .globl main             # 导出函数符号，使链接器可见
    main:                       # 函数入口标签
    # Function: main (params: 0)
    pushq %rbp                    # 保存调用者的帧基址到栈上
    movq %rsp, %rbp               # 建立新栈帧：rbp = rsp（此后用 rbp+偏移访问局部）
    subq $64, %rsp              # 预留局部变量栈空间（16B 对齐）
    # function call
    callq f                  # 调用函数 f
    # function call
    callq h                  # 调用函数 h
    # return expr
    movq g(%rip), %rax    # 加载全局变量 g 到 rax（RIP 相对寻址）
    leave                         # 恢复栈帧（movq %rbp,%rsp; popq %rbp）
    ret                           # 返回调用者（从栈上弹出返回地址）
    

    .data
    .globl g             # 导出全局变量符号
    .align 8                # 8 字节对齐
g:                    # 全局变量标签
    .quad 0              # 初始化值：0

