# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl Point_Point
    Point_Point:
    # Function: Point (params: 2)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq %rsi, -16(%rbp)    # param: px
    movq %rdx, -24(%rbp)    # param: py
    movq -16(%rbp), %rax    # load px
    movq -8(%rbp), %rcx    # load this
    movq %rax, 0(%rcx)    # init field x
    movq -24(%rbp), %rax    # load py
    movq -8(%rbp), %rcx    # load this
    movq %rax, 4(%rcx)    # init field y
    movq -8(%rbp), %rax    # return this from constructor
    leave
    ret
    
        .globl Point_sum
    Point_sum:
    # Function: sum (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    # return expr
    # binary expr
    movq -8(%rbp), %rax    # load this
    movl 0(%rax), %eax    # load .x (offset 0)
    pushq %rax
    movq -8(%rbp), %rax    # load this
    movl 4(%rax), %eax    # load .y (offset 4)
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    leave
    ret
    leave
    ret
    
        .globl Point_dtor
    Point_dtor:
    # Function: ~Point (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    movq %rdi, -8(%rbp)
    movq $0, %rax
    leave
    ret
    
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp    # frame for locals
    # var p = ...
    # new Point()
    movq $8, %rdi             # malloc size
    callq malloc                  # allocate memory
    pushq %rax                    # save allocated objPtr
    movq $10, %rax           # int literal
    pushq %rax
    movq $20, %rax           # int literal
    pushq %rax
    popq %rdx
    popq %rsi
    movq (%rsp), %rdi             # this pointer
    callq Point_Point              # call constructor
    popq %rax                     # return objPtr
    # end new Point()
    movq %rax, -16(%rbp)    # store to p
    # return expr
    # function call
    movq -16(%rbp), %rax    # load p
    pushq %rax                   # save this pointer
    popq %rdi                    # this pointer
    callq Point_sum               # method call
    leave
    ret
    leave
    ret
    
