# ═══════════════════════════════════════════════════════════
# Mini C++ Compiler - x86-64 Assembly Output
# Generated by minicc
# ═══════════════════════════════════════════════════════════

    .text
        .globl main
    main:
    # Function: main (params: 0)
    pushq %rbp
    movq %rsp, %rbp
    subq $64, %rsp
    # var v = ...
    # binary expr
    movq $20, %rax           # int literal
    pushq %rax
    movq $20, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    movq %rax, -16(%rbp)    # store to v
    # var w = ...
    # binary expr
    movq $1, %rax           # int literal
    pushq %rax
    movq $42, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    movq %rax, -24(%rbp)    # store to w
    # var c = ...
    # binary expr
    movq $20, %rax           # int literal
    pushq %rax
    movq $20, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    movq %rax, -32(%rbp)    # store to c
    # return expr
    # binary expr
    # binary expr
    # binary expr
    movq -16(%rbp), %rax    # load v
    pushq %rax
    movq -24(%rbp), %rax    # load w
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    pushq %rax
    movq -32(%rbp), %rax    # load c
    movq %rax, %rcx
    popq %rax
    addq %rcx, %rax              # +
    pushq %rax
    movq $123, %rax           # int literal
    movq %rax, %rcx
    popq %rax
    subq %rcx, %rax              # -
    leave
    ret
    leave
    ret
    
