// =============================================================================
// 阶段 5：代码生成器实现 —— x86-64 汇编输出
// =============================================================================
// 这是编译器的"最后一公里"：将 AST 翻译为真实的机器指令。
//
// 核心转换示例：
//   源码: u.age = 20;
//   汇编: movl $20, -8(%rbp)    # 直接硬编码偏移量，字段名已消失
//
//   源码: ptr->foo();  (虚函数)
//   汇编: movq (%rax), %rax     # (a) 从对象读出 _vptr
//         movq 0(%rax), %rax    # (b) 加上 vtable[0] 偏移
//         callq *%rax           # (c) 跳转到该地址执行
//
// 目标架构：x86-64, System V AMD64 ABI
//   - 参数传递：rdi, rsi, rdx, rcx, r8, r9
//   - 返回值：rax
//   - 栈对齐：16 字节
// =============================================================================

#include "codegen.h"
#include "template_instantiation.h"
#include <format>
#include <algorithm>
#include <cassert>

namespace minicc {

CodeGen::CodeGen() = default;

// ─────────────────────────────────────────────────────────────────────────────
// 辅助函数
// ─────────────────────────────────────────────────────────────────────────────
std::string CodeGen::newLabel(const std::string& prefix) {
    return std::format("{}_{}", prefix, m_labelCounter++);
}

void CodeGen::emit(const std::string& line) {
    m_code << "    " << line << "\n";
}

void CodeGen::emitData(const std::string& line) {
    m_data << line << "\n";
}

void CodeGen::emitRodata(const std::string& line) {
    m_rodata << line << "\n";
}

void CodeGen::emitComment(const std::string& comment) {
    m_code << "    # " << comment << "\n";
}

std::string CodeGen::addStringLiteral(const std::string& value) {
    std::string label = newLabel("str");
    m_stringLiterals.emplace_back(label, value);
    return label;
}

// ─────────────────────────────────────────────────────────────────────────────
// 主入口：生成整个编译单元的汇编
// ─────────────────────────────────────────────────────────────────────────────
std::string CodeGen::generate(
    const TranslationUnit& unit,
    const std::unordered_map<std::string, TypePtr>& classTypes,
    const std::vector<FuncDeclPtr>& functions) {

    m_classTypes = &classTypes;

    // ── 生成数据段：vtable、RTTI、字符串字面量 ──

    // 为每个有虚函数的类生成 vtable 和 RTTI
    for (auto& [name, type] : classTypes) {
        if (type->classLayout.hasVTable) {
            emitVTable(name, type);
            emitRTTI(name, type);
        }
    }

    // ── 生成代码段：所有函数 ──
    for (auto& func : functions) {
        if (func->body) {
            emitFunction(func);
        }
    }

    // ── 生成只读数据段：字符串字面量 ──
    emitStringLiterals();

    // ── 拼装最终输出 ──
    std::ostringstream output;

    output << "# ═══════════════════════════════════════════════════════════\n";
    output << "# Mini C++ Compiler - x86-64 Assembly Output\n";
    output << "# Generated by minicc\n";
    output << "# ═══════════════════════════════════════════════════════════\n\n";

    output << "    .text\n";
    output << m_code.str();

    if (!m_data.str().empty()) {
        output << "\n    .data\n";
        output << m_data.str();
    }

    if (!m_rodata.str().empty()) {
        output << "\n    .section .rodata\n";
        output << m_rodata.str();
    }

    return output.str();
}

// ═════════════════════════════════════════════════════════════════════════════
// vtable 生成
// ═════════════════════════════════════════════════════════════════════════════
// vtable 在内存中的布局（GCC ABI 风格简化版）：
//
//   _ZTV7MyClass:
//       .quad 0                  # 偏移量到顶层（通常为0）
//       .quad _ZTI7MyClass       # vtable[-1]: RTTI type_info 指针
//       .quad _ZN7MyClass3fooEv  # vtable[0]:  第一个虚函数
//       .quad _ZN7MyClass3barEv  # vtable[1]:  第二个虚函数
//
// 对象的 _vptr 指向 vtable[0]（即跳过前两个槽位）。
// 当需要 RTTI 时，通过 _vptr[-1] 获取 type_info 指针。
// ═════════════════════════════════════════════════════════════════════════════
void CodeGen::emitVTable(const std::string& className, TypePtr classType) {
    std::string vtableLabel = NameMangler::mangleVTable(className);
    std::string rttiLabel = NameMangler::mangleRTTI(className);

    emitData(std::format("    .globl {}", vtableLabel));
    emitData(std::format("    .align 8", vtableLabel));
    emitData(std::format("{}:", vtableLabel));
    emitData("    .quad 0                    # offset to top");
    emitData(std::format("    .quad {}       # RTTI type_info pointer (vtable[-1])",
        rttiLabel));

    // 虚函数条目
    for (auto& entry : classType->classLayout.vtableEntries) {
        emitData(std::format("    .quad {}   # vtable[{}]: {}",
            entry.mangledName, entry.index, entry.mangledName));
    }

    emitData("");
}

// ═════════════════════════════════════════════════════════════════════════════
// RTTI type_info 生成
// ═════════════════════════════════════════════════════════════════════════════
// type_info 结构（简化版）：
//   _ZTI7MyClass:
//       .quad _ZTVN10__cxxabiv117__class_type_infoE  # vtable for type_info
//       .quad .Ltype_name_MyClass                     # 类型名称字符串
//
// 这使得运行时可以通过 typeid() 获取类型信息。
// ═════════════════════════════════════════════════════════════════════════════
void CodeGen::emitRTTI(const std::string& className, TypePtr) {
    std::string rttiLabel = NameMangler::mangleRTTI(className);
    std::string nameLabel = std::format(".Ltype_name_{}", className);

    // RTTI 结构
    emitData(std::format("    .globl {}", rttiLabel));
    emitData(std::format("    .align 8"));
    emitData(std::format("{}:", rttiLabel));
    emitData(std::format("    .quad 0                    # type_info vtable (simplified)"));
    emitData(std::format("    .quad {}                 # type name string", nameLabel));

    // 类型名称字符串
    emitRodata(std::format("{}:", nameLabel));
    emitRodata(std::format("    .string \"{}\"           # type name", className));

    emitData("");
}

// ─────────────────────────────────────────────────────────────────────────────
// 字符串字面量
// ─────────────────────────────────────────────────────────────────────────────
void CodeGen::emitStringLiterals() {
    for (auto& [label, value] : m_stringLiterals) {
        emitRodata(std::format("{}:", label));
        emitRodata(std::format("    .string \"{}\"", value));
    }
}

// ═════════════════════════════════════════════════════════════════════════════
// 函数生成
// ═════════════════════════════════════════════════════════════════════════════
// 函数结构（x86-64 标准栈帧）：
//
//   func:
//       pushq %rbp              # 保存旧的基指针
//       movq  %rsp, %rbp        # 设置新的基指针
//       subq  $N, %rsp          # 分配局部变量空间
//
//       ... 函数体 ...
//
//       leave                   # 恢复栈帧
//       ret                     # 返回
// ═════════════════════════════════════════════════════════════════════════════
void CodeGen::emitFunction(FuncDeclPtr func) {
    m_localVars.clear();
    m_currentStackOffset = 0;
    m_currentClassName = func->ownerClassName;

    // 查找当前类类型
    m_currentClassType = nullptr;
    if (!m_currentClassName.empty() && m_classTypes) {
        auto it = m_classTypes->find(m_currentClassName);
        if (it != m_classTypes->end()) {
            m_currentClassType = it->second;
        }
    }

    // 确定函数名
    std::string funcName = func->mangledName.empty()
        ? func->name : func->mangledName;

    emit(std::format("    .globl {}", funcName));
    emit(std::format("{}:", funcName));

    emitComment(std::format("Function: {} (params: {})",
        func->name, func->parameters.size()));

    // 函数序言（Prologue）
    emit("pushq %rbp");
    emit("movq %rsp, %rbp");

    // 预留局部变量空间（先扫描一遍计算大小）
    // 简化：先预留 64 字节
    emit("subq $64, %rsp");

    // 保存参数到栈上
    static const char* paramRegs[] = {"rdi", "rsi", "rdx", "rcx", "r8", "r9"};
    int paramOffset = -8;

    // 如果是成员函数，第一个参数是 this 指针
    if (!func->ownerClassName.empty()) {
        m_localVars["this"] = paramOffset;
        emit(std::format("movq %{}, {}(%rbp)", paramRegs[0], paramOffset));
        paramOffset -= 8;
    }

    for (size_t i = 0; i < func->parameters.size() && i < 6; i++) {
        size_t regIdx = func->ownerClassName.empty() ? i : i + 1;
        if (regIdx < 6) {
            m_localVars[func->parameters[i].name] = paramOffset;
            emit(std::format("movq %{}, {}(%rbp)    # param: {}",
                paramRegs[regIdx], paramOffset, func->parameters[i].name));
            paramOffset -= 8;
        }
    }

    m_currentStackOffset = paramOffset;

    // 生成函数体
    if (func->body) {
        for (auto& stmt : func->body->statements) {
            emitStmt(stmt);
        }
    }

    // 如果函数没有显式 return，添加默认返回
    if (func->returnType->isVoid()) {
        emit("movq $0, %rax");
    }

    // 函数尾声（Epilogue）
    emit("leave");
    emit("ret");
    emit("");
}

// ═════════════════════════════════════════════════════════════════════════════
// 语句生成
// ═════════════════════════════════════════════════════════════════════════════
void CodeGen::emitStmt(StmtPtr stmt) {
    if (auto s = std::dynamic_pointer_cast<BlockStmt>(stmt))
        emitBlockStmt(s);
    else if (auto s = std::dynamic_pointer_cast<VarDeclStmt>(stmt))
        emitVarDecl(s);
    else if (auto s = std::dynamic_pointer_cast<AssignStmt>(stmt))
        emitAssign(s);
    else if (auto s = std::dynamic_pointer_cast<ReturnStmt>(stmt))
        emitReturn(s);
    else if (auto s = std::dynamic_pointer_cast<IfStmt>(stmt))
        emitIf(s);
    else if (auto s = std::dynamic_pointer_cast<WhileStmt>(stmt))
        emitWhile(s);
    else if (auto s = std::dynamic_pointer_cast<ExprStmt>(stmt))
        emitExprStmt(s);
}

void CodeGen::emitBlockStmt(std::shared_ptr<BlockStmt> block) {
    for (auto& stmt : block->statements) {
        emitStmt(stmt);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// 变量声明
// ─────────────────────────────────────────────────────────────────────────────
// auto x = 10; 到了这里，auto 已经被替换为 int，所以直接生成：
//   movq $10, -offset(%rbp)
// ─────────────────────────────────────────────────────────────────────────────
void CodeGen::emitVarDecl(std::shared_ptr<VarDeclStmt> decl) {
    m_currentStackOffset -= 8;
    m_localVars[decl->name] = m_currentStackOffset;

    if (decl->initializer) {
        emitComment(std::format("var {} = ...", decl->name));
        emitExpr(decl->initializer);
        emit(std::format("movq %rax, {}(%rbp)    # store to {}",
            m_currentStackOffset, decl->name));
    } else {
        // 零初始化
        emit(std::format("movq $0, {}(%rbp)    # zero init {}",
            m_currentStackOffset, decl->name));
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// 赋值语句
// ─────────────────────────────────────────────────────────────────────────────
// 普通字段赋值的消除：
//   源码: u.age = 20;
//   编译期: age 的偏移量是 4（假设）
//   汇编: movl $20, 4(%rax)    # 直接用偏移量，字段名已消失
// ─────────────────────────────────────────────────────────────────────────────
void CodeGen::emitAssign(std::shared_ptr<AssignStmt> stmt) {
    // 计算右值到 rax
    emitExpr(stmt->value);

    // 赋值目标
    if (auto var = std::dynamic_pointer_cast<VarExpr>(stmt->target)) {
        auto it = m_localVars.find(var->name);
        if (it != m_localVars.end()) {
            emit(std::format("movq %rax, {}(%rbp)    # {} = ...",
                it->second, var->name));
        }
    }
    else if (auto mem = std::dynamic_pointer_cast<MemberExpr>(stmt->target)) {
        // ─── 字段访问的消除 ───
        // 将 obj.field = value 转化为 [objAddr + fieldOffset] = value
        emitComment(std::format("member assign: .{} = ...", mem->memberName));

        // 先计算对象地址到 rcx
        emitExpr(mem->object);
        emit("movq %rax, %rcx                # object address");

        // 计算右值到 rax
        emitExpr(stmt->value);

        // 查找字段偏移量
        if (mem->object->resolvedType) {
            TypePtr objType = mem->object->resolvedType;
            if (mem->isArrow && objType->isPointer()) {
                objType = objType->pointeeType;
            }
            if (objType->isClass()) {
                auto field = objType->classLayout.findField(mem->memberName);
                if (field) {
                    emit(std::format("movl %eax, {}(%rcx)    # .{} (offset {})",
                        field->offset, mem->memberName, field->offset));
                    return;
                }
            }
        }

        // 如果找不到偏移量，生成通用代码
        emit("movq %rax, (%rcx)              # store to member");
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// return 语句
// ─────────────────────────────────────────────────────────────────────────────
void CodeGen::emitReturn(std::shared_ptr<ReturnStmt> stmt) {
    if (stmt->value) {
        emitComment("return expr");
        emitExpr(stmt->value);
        // 返回值已经在 rax 中
    } else {
        emit("movq $0, %rax                  # return void");
    }
    emit("leave");
    emit("ret");
}

// ─────────────────────────────────────────────────────────────────────────────
// if 语句
// ─────────────────────────────────────────────────────────────────────────────
// 生成模式：
//   <condition>
//   testq %rax, %rax
//   je .L_else_N
//   <then branch>
//   jmp .L_end_N
//   .L_else_N:
//   <else branch>
//   .L_end_N:
// ─────────────────────────────────────────────────────────────────────────────
void CodeGen::emitIf(std::shared_ptr<IfStmt> stmt) {
    std::string elseLabel = newLabel("else");
    std::string endLabel = newLabel("endif");

    emitComment("if condition");
    emitExpr(stmt->condition);
    emit("testq %rax, %rax");
    emit(std::format("je {}", stmt->elseBranch ? elseLabel : endLabel));

    emitComment("then branch");
    emitStmt(stmt->thenBranch);

    if (stmt->elseBranch) {
        emit(std::format("jmp {}", endLabel));
        emit(std::format("{}:", elseLabel));
        emitComment("else branch");
        emitStmt(stmt->elseBranch);
    }

    emit(std::format("{}:", endLabel));
}

// ─────────────────────────────────────────────────────────────────────────────
// while 语句
// ─────────────────────────────────────────────────────────────────────────────
// 生成模式：
//   .L_begin_N:
//   <condition>
//   testq %rax, %rax
//   je .L_end_N
//   <body>
//   jmp .L_begin_N
//   .L_end_N:
// ─────────────────────────────────────────────────────────────────────────────
void CodeGen::emitWhile(std::shared_ptr<WhileStmt> stmt) {
    std::string beginLabel = newLabel("while_begin");
    std::string endLabel = newLabel("while_end");

    emit(std::format("{}:", beginLabel));
    emitComment("while condition");
    emitExpr(stmt->condition);
    emit("testq %rax, %rax");
    emit(std::format("je {}", endLabel));

    emitComment("while body");
    emitStmt(stmt->body);
    emit(std::format("jmp {}", beginLabel));

    emit(std::format("{}:", endLabel));
}

void CodeGen::emitExprStmt(std::shared_ptr<ExprStmt> stmt) {
    emitExpr(stmt->expr);
}

// ═════════════════════════════════════════════════════════════════════════════
// 表达式生成
// ═════════════════════════════════════════════════════════════════════════════
// 核心约定：每个表达式的结果放在 rax 寄存器中
// ═════════════════════════════════════════════════════════════════════════════
void CodeGen::emitExpr(ExprPtr expr) {
    if (auto e = std::dynamic_pointer_cast<IntLiteralExpr>(expr))
        emitIntLiteral(e);
    else if (auto e = std::dynamic_pointer_cast<BoolLiteralExpr>(expr))
        emitBoolLiteral(e);
    else if (auto e = std::dynamic_pointer_cast<StringLiteralExpr>(expr))
        emitStringLiteral(e);
    else if (auto e = std::dynamic_pointer_cast<VarExpr>(expr))
        emitVar(e);
    else if (auto e = std::dynamic_pointer_cast<BinaryExpr>(expr))
        emitBinary(e);
    else if (auto e = std::dynamic_pointer_cast<UnaryExpr>(expr))
        emitUnary(e);
    else if (auto e = std::dynamic_pointer_cast<CallExpr>(expr))
        emitCall(e);
    else if (auto e = std::dynamic_pointer_cast<MemberExpr>(expr))
        emitMember(e);
    else if (auto e = std::dynamic_pointer_cast<NewExpr>(expr))
        emitNew(e);
    else if (auto e = std::dynamic_pointer_cast<ThisExpr>(expr))
        emitThis(e);
    else if (std::dynamic_pointer_cast<NullptrLiteralExpr>(expr)) {
        emit("xorq %rax, %rax                # nullptr = 0");
    }
}

void CodeGen::emitIntLiteral(std::shared_ptr<IntLiteralExpr> expr) {
    emit(std::format("movq ${}, %rax           # int literal", expr->value));
}

void CodeGen::emitBoolLiteral(std::shared_ptr<BoolLiteralExpr> expr) {
    emit(std::format("movq ${}, %rax           # bool literal",
        expr->value ? 1 : 0));
}

void CodeGen::emitStringLiteral(std::shared_ptr<StringLiteralExpr> expr) {
    std::string label = addStringLiteral(expr->value);
    emit(std::format("leaq {}(%rip), %rax      # string literal", label));
}

void CodeGen::emitVar(std::shared_ptr<VarExpr> expr) {
    // 先查局部变量
    auto it = m_localVars.find(expr->name);
    if (it != m_localVars.end()) {
        emit(std::format("movq {}(%rbp), %rax    # load {}",
            it->second, expr->name));
        return;
    }

    // 如果在类方法中，查类字段（通过 this 指针访问）
    if (!m_currentClassName.empty() && m_currentClassType) {
        auto field = m_currentClassType->classLayout.findField(expr->name);
        if (field) {
            // 通过 this 指针访问字段
            auto thisIt = m_localVars.find("this");
            if (thisIt != m_localVars.end()) {
                emit(std::format("movq {}(%rbp), %rax    # load this", thisIt->second));
                emit(std::format("movl {}(%rax), %eax    # load .{} (offset {})",
                    field->offset, expr->name, field->offset));
                return;
            }
        }
    }

    emit(std::format("# WARNING: undefined variable '{}'", expr->name));
    emit("xorq %rax, %rax");
}

// ─────────────────────────────────────────────────────────────────────────────
// 二元表达式
// ─────────────────────────────────────────────────────────────────────────────
// 生成模式：
//   <left>  → rax
//   pushq %rax           # 保存左操作数
//   <right> → rax
//   movq %rax, %rcx      # 右操作数移到 rcx
//   popq %rax            # 恢复左操作数
//   <operation>          # 执行运算
// ─────────────────────────────────────────────────────────────────────────────
void CodeGen::emitBinary(std::shared_ptr<BinaryExpr> expr) {
    emitComment("binary expr");

    // 左操作数 → rax → 压栈
    emitExpr(expr->left);
    emit("pushq %rax");

    // 右操作数 → rax → rcx
    emitExpr(expr->right);
    emit("movq %rax, %rcx");

    // 恢复左操作数到 rax
    emit("popq %rax");

    switch (expr->op) {
        case BinaryOp::Add:
            emit("addq %rcx, %rax              # +");
            break;
        case BinaryOp::Sub:
            emit("subq %rcx, %rax              # -");
            break;
        case BinaryOp::Mul:
            emit("imulq %rcx, %rax             # *");
            break;
        case BinaryOp::Div:
            emit("cqto                         # sign extend rax → rdx:rax");
            emit("idivq %rcx                   # / (rax = quotient)");
            break;
        case BinaryOp::Mod:
            emit("cqto");
            emit("idivq %rcx                   # % (rdx = remainder)");
            emit("movq %rdx, %rax");
            break;
        case BinaryOp::Eq:
            emit("cmpq %rcx, %rax");
            emit("sete %al                     # ==");
            emit("movzbq %al, %rax");
            break;
        case BinaryOp::Neq:
            emit("cmpq %rcx, %rax");
            emit("setne %al                    # !=");
            emit("movzbq %al, %rax");
            break;
        case BinaryOp::Lt:
            emit("cmpq %rcx, %rax");
            emit("setl %al                     # <");
            emit("movzbq %al, %rax");
            break;
        case BinaryOp::Gt:
            emit("cmpq %rcx, %rax");
            emit("setg %al                     # >");
            emit("movzbq %al, %rax");
            break;
        case BinaryOp::Le:
            emit("cmpq %rcx, %rax");
            emit("setle %al                    # <=");
            emit("movzbq %al, %rax");
            break;
        case BinaryOp::Ge:
            emit("cmpq %rcx, %rax");
            emit("setge %al                    # >=");
            emit("movzbq %al, %rax");
            break;
        case BinaryOp::And:
            emit("andq %rcx, %rax              # &&");
            break;
        case BinaryOp::Or:
            emit("orq %rcx, %rax               # ||");
            break;
    }
}

void CodeGen::emitUnary(std::shared_ptr<UnaryExpr> expr) {
    emitExpr(expr->operand);

    switch (expr->op) {
        case UnaryOp::Neg:
            emit("negq %rax                    # negate");
            break;
        case UnaryOp::Not:
            emit("testq %rax, %rax");
            emit("sete %al                     # logical not");
            emit("movzbq %al, %rax");
            break;
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// 函数调用
// ─────────────────────────────────────────────────────────────────────────────
// System V AMD64 ABI 参数传递约定：
//   第1个参数: rdi
//   第2个参数: rsi
//   第3个参数: rdx
//   第4个参数: rcx
//   第5个参数: r8
//   第6个参数: r9
//   返回值: rax
// ─────────────────────────────────────────────────────────────────────────────
void CodeGen::emitCall(std::shared_ptr<CallExpr> expr) {
    emitComment("function call");

    // 检查是否是方法调用
    if (auto mem = std::dynamic_pointer_cast<MemberExpr>(expr->callee)) {
        if (mem->isMethodCall || (mem->object && mem->object->resolvedType)) {
            TypePtr objType = mem->object->resolvedType;
            if (mem->isArrow && objType && objType->isPointer()) {
                objType = objType->pointeeType;
            }

            // 检查是否是虚函数调用
            if (objType && objType->isClass() && m_classTypes) {
                auto it = m_classTypes->find(objType->name);
                if (it != m_classTypes->end()) {
                    auto& layout = it->second->classLayout;
                    for (auto& entry : layout.vtableEntries) {
                        if (entry.mangledName.find(mem->memberName) != std::string::npos) {
                            // 这是虚函数调用！
                            emitVirtualCall(objType->name, mem->memberName,
                                          expr->arguments, entry.index);
                            return;
                        }
                    }
                }
            }

            // 普通方法调用（非虚函数）
            // 先计算对象地址作为第一个参数（this 指针）
            emitExpr(mem->object);
            emit("pushq %rax                   # save this pointer");

            // 计算参数
            for (size_t i = 0; i < expr->arguments.size() && i < 5; i++) {
                emitExpr(expr->arguments[i]);
                emit("pushq %rax");
            }

            // 恢复参数到寄存器
            for (int i = static_cast<int>(expr->arguments.size()) - 1; i >= 0 && i < 5; i--) {
                static const char* regs[] = {"rsi", "rdx", "rcx", "r8", "r9"};
                emit(std::format("popq %{}", regs[i]));
            }

            // this 指针到 rdi
            emit("popq %rdi                    # this pointer");

            // 调用
            std::string funcName;
            if (objType && objType->isClass()) {
                funcName = objType->name + "_" + mem->memberName;
            } else {
                funcName = mem->memberName;
            }
            emit(std::format("callq {}               # method call", funcName));
            return;
        }
    }

    // 普通函数调用
    // 计算参数并放入对应寄存器
    for (size_t i = 0; i < expr->arguments.size() && i < 6; i++) {
        emitExpr(expr->arguments[i]);
        emit("pushq %rax");
    }

    // 恢复参数到寄存器（逆序）
    static const char* regs[] = {"rdi", "rsi", "rdx", "rcx", "r8", "r9"};
    for (int i = static_cast<int>(expr->arguments.size()) - 1; i >= 0; i--) {
        if (i < 6) {
            emit(std::format("popq %{}", regs[i]));
        }
    }

    // 确定函数名
    std::string funcName;
    if (auto var = std::dynamic_pointer_cast<VarExpr>(expr->callee)) {
        funcName = var->name;
    }

    emit(std::format("callq {}               # function call", funcName));
}

// ═════════════════════════════════════════════════════════════════════════════
// 虚函数调用 —— 编译器最精彩的"三部曲"
// ═════════════════════════════════════════════════════════════════════════════
//
// ptr->vfunc(args) 在机器码层面绝对不能直接 call vfunc！
// 因为编译期不知道 ptr 指向哪个具体类型（多态），
// 必须通过虚函数表在运行期动态查找到真正的函数地址。
//
// 汇编三部曲：
//
//   (a) 从对象读出 _vptr 机器地址
//       movq (objAddr), %rax          # rax = obj._vptr
//
//   (b) 加上虚函数在表中的 Index 偏移量
//       movq index*8(%rax), %rax      # rax = vtable[index]
//
//   (c) 跳转到该地址执行
//       callq *%rax                   # 间接调用
//
// 这就是"编译期看符号，运行期看偏移量"的终极体现：
//   编译期：ptr->vfunc()  → 查符号表得到 vtable index
//   运行期：[ptr+0] → vtable → [vtable+index*8] → 真实函数地址 → 执行
// ═════════════════════════════════════════════════════════════════════════════
void CodeGen::emitVirtualCall(
    const std::string& className,
    const std::string& methodName,
    const std::vector<ExprPtr>& args,
    uint32_t vtableIndex) {

    emitComment(std::format("VIRTUAL CALL: {}::{} (vtable[{}])",
        className, methodName, vtableIndex));

    // ─── 准备参数 ───
    // 第一个参数是 this 指针（对象地址）

    // 先计算参数（跳过 this）
    for (size_t i = 0; i < args.size() && i < 5; i++) {
        emitExpr(args[i]);
        emit("pushq %rax");
    }

    // 计算对象地址（this 指针）
    emit("movq %rdi, %rbx              # save object pointer");

    // 恢复参数到寄存器
    for (int i = static_cast<int>(args.size()) - 1; i >= 0 && i < 5; i--) {
        static const char* regs[] = {"rsi", "rdx", "rcx", "r8", "r9"};
        emit(std::format("popq %{}", regs[i]));
    }

    // this 指针到 rdi
    emit("movq %rbx, %rdi              # this pointer");

    // ─── 虚函数调用三部曲 ───

    // (a) 从对象偏移量 +0 处读出 _vptr 指针
    emit("# ═══ Virtual Call Step (a): Read _vptr from object ═══");
    emit("movq (%rdi), %rax            # rax = obj._vptr (at offset 0)");

    // (b) 从 vtable 中加上 index 偏移量，读出真正的函数地址
    //     vtable 布局：[0] = offset-to-top, [1] = RTTI, [2+] = 虚函数
    //     所以实际偏移量 = (index + 2) * 8
    uint32_t vtableOffset = (vtableIndex + 2) * 8;
    emit("# ═══ Virtual Call Step (b): Load function address from vtable ═══");
    emit(std::format("movq {}(%rax), %rax       # rax = vtable[{}] (offset {})",
        vtableOffset, vtableIndex, vtableOffset));

    // (c) 间接跳转到该地址执行
    emit("# ═══ Virtual Call Step (c): Jump to the real function ═══");
    emit("callq *%rax                  # indirect call via vtable");

    emitComment(std::format("END VIRTUAL CALL {}::{}", className, methodName));
}

// ─────────────────────────────────────────────────────────────────────────────
// 成员访问
// ─────────────────────────────────────────────────────────────────────────────
// obj.field 的消除过程：
//   编译期：查 ClassLayout 得到 field 的偏移量
//   汇编：  [objAddr + fieldOffset] → rax
//   字段名在此刻彻底消失，只剩下数字偏移量。
// ─────────────────────────────────────────────────────────────────────────────
void CodeGen::emitMember(std::shared_ptr<MemberExpr> expr) {
    emitComment(std::format("member access: .{}", expr->memberName));

    // 计算对象地址
    emitExpr(expr->object);

    TypePtr objType = expr->object->resolvedType;
    if (expr->isArrow && objType && objType->isPointer()) {
        // 对于 -> 操作，对象本身就是一个指针
        // 不需要额外解引用
    } else if (objType && !objType->isPointer()) {
        // 对于 . 操作，如果对象不是指针，需要获取其地址
        // 这里简化处理
    }

    if (objType) {
        TypePtr actualType = objType;
        if (expr->isArrow && objType->isPointer()) {
            actualType = objType->pointeeType;
        }

        if (actualType && actualType->isClass()) {
            auto field = actualType->classLayout.findField(expr->memberName);
            if (field) {
                // 直接用偏移量访问字段
                emit(std::format("movq {}(%rax), %rax    # .{} (offset {})",
                    field->offset, expr->memberName, field->offset));
                return;
            }
        }
    }

    // 默认：偏移量 0
    emit("movq (%rax), %rax            # member access (unknown offset)");
}

// ─────────────────────────────────────────────────────────────────────────────
// new 表达式（简化版：调用 malloc）
// ─────────────────────────────────────────────────────────────────────────────
// new MyClass() 被翻译为：
//   1. 调用 malloc(classSize) 分配内存
//   2. 设置 _vptr 指向该类的 vtable
//   3. 返回对象指针
// ─────────────────────────────────────────────────────────────────────────────
void CodeGen::emitNew(std::shared_ptr<NewExpr> expr) {
    emitComment(std::format("new {}()", expr->className));

    // 查找类的大小
    uint32_t size = 8; // 默认大小
    std::string vtableLabel;
    bool hasVTable = false;

    if (m_classTypes) {
        auto it = m_classTypes->find(expr->className);
        if (it != m_classTypes->end()) {
            size = it->second->classLayout.totalSize;
            if (size == 0) size = 8;
            hasVTable = it->second->classLayout.hasVTable;
            if (hasVTable) {
                vtableLabel = NameMangler::mangleVTable(expr->className);
            }
        }
    }

    // 调用 malloc
    emit(std::format("movq ${}, %rdi             # malloc size", size));
    emit("callq malloc                  # allocate memory");

    if (hasVTable) {
        // 设置 _vptr：对象偏移量 0 处 = vtable 地址 + 16
        // （跳过 offset-to-top 和 RTTI 指针）
        emit(std::format("leaq {}(%rip), %rcx    # vtable address", vtableLabel));
        emit("addq $16, %rcx              # skip to vtable[0]");
        emit("movq %rcx, (%rax)           # obj._vptr = vtable");
    }

    emitComment(std::format("end new {}()", expr->className));
}

// ─────────────────────────────────────────────────────────────────────────────
// this 表达式
// ─────────────────────────────────────────────────────────────────────────────
void CodeGen::emitThis(std::shared_ptr<ThisExpr>) {
    auto it = m_localVars.find("this");
    if (it != m_localVars.end()) {
        emit(std::format("movq {}(%rbp), %rax    # this pointer", it->second));
    } else {
        emit("# WARNING: 'this' used outside of class method");
        emit("xorq %rax, %rax");
    }
}

} // namespace minicc
